<!DOCTYPE HTML>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Hotel Club - Great Holidays - Banner</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- include bootstrap -->
	<link href="bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
	<link href="bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
	<link href="css/hc_great_holidays.css" rel="stylesheet" media="screen">
</head>
<body>
	<div class="container">
		
		<!-- START VIEW PARTIAL: banner.phtml -->
		<div id="banner" class="subContainer">
				<!-- Desktop Search Widget -->
				<div class="clearfix"></div>
					<div id="dkt_searchBot" class="visible-desktop">
						<!-- search -->
						<form class="form-inline datepicker" method="get" name="searchBot role="form">
							<div class=" where">
								<h2>Find a hotel deal</h2>
								<p>Where</p>
								<input type="text"  class="form-control input-md" placeholder="Location.." id="locationText">
							</div>	
							<div class="form-group ">
								<p>Check-in</p>
								<input type="text" class="form-control input-sm"  placeholder="dd/mm/yy">
							</div>
							<div class="form-group ">
								<p>Check-out</p>
								<input type="text" class="form-control input-sm "  placeholder="dd/mm/yy">
							</div>								
							<div class="controls">
							<div class="errorMessage">&nbsp;</div>	
								<input type="button" class="btn btn-default col-md-offset-8" onclick="doSearch(this.form)" value="Search" name="search">
							</div>
							<div class=" promo-code">                        
								<p>I have a promotion code</p>
								<input type="text"  name="couponCode" id="couponCode" class="form-control input-md" placeholder="Location.." id="locationText">
							</div> 
							<div class="search_contacts row">
							<div class="glyphicon glyphicon-earphone col-md-1">
							</div>
							<div class=" help col-md-8">
							<p>Need Help to book ?</p>
							<p>1300 854 585 </p>
							</div>
							</div>
						</form>					
					</div>
				
				<!-- /Desktop Search Widget -->
				<!-- Tablet search widget -->
				<div id="tbt_searchBot" class="visible-tablet">
						<!-- search -->
						<form class="form-inline datepicker" method="get" name="searchBot role="form">
							<div class=" where">
								<h2>Find a hotel deal</h2>
								<p>Where</p>
								<input type="text"  class="form-control input-md" placeholder="Location.." id="locationText">
							</div>	
							<div class="form-group ">
								<p>Check-in</p>
								<input type="text" class="form-control input-sm"  placeholder="dd/mm/yy">
							</div>
							<div class="form-group ">
								<p>Check-out</p>
								<input type="text" class="form-control input-sm "  placeholder="dd/mm/yy">
							</div>								
							<div class="controls">
							<div class="errorMessage">&nbsp;</div>	
								<input type="button" class="btn btn-default col-md-offset-8" onclick="doSearch(this.form)" value="Search" name="search">
							</div>
							<div class=" promo-code">                        
								<p>I have a promotion code</p>
								<input type="text"  name="couponCode" id="couponCode" class="form-control input-md" placeholder="Location.." id="locationText">
							</div> 
							
						</form>					
					</div>
			<!-- /Tablet search widget -->
			<!-- carousel -->
			<div id="dkt_carousel" class="carousel slide" data-ride="carousel" data-interval="2500">
				<ol class="carousel-indicators">
					<li data-target="#dkt_carousel" data-slide-to="0" class="active"></li>
					<li data-target="#dkt_carousel" data-slide-to="1"></li>
					<li data-target="#dkt_carousel" data-slide-to="2"></li>
				</ol>
				<!-- Carousel items -->
				<div class="carousel-inner">
					<div class="item active">
						<img src="img/carousel_item1.png" alt="Member"/>
						<div class="row">
							<div class="carousel-caption visible-tablet col-md-offset-3">
								<h2>Great Holiday Sale ----</h2>
								<h3>Save Upto 50% of hotels </h3>
								<h5>Plus Get Up to 7% Member Rewards</h5>
								<h6>* conditions apply<h6>
							</div>
						</div>
					</div>
					<div class="item">
						<img src="img/carousel_item2.png" alt="Member"/>
						<div class="row">
							<div class="carousel-caption visible-tablet col-xs-6">
								<h2>Great Holiday Sale ----</h2>
								<h3>Save Upto 50% of hotels </h3>
								<h5>Plus Get Up to 7% Member Rewards</h5>
								<h6>* conditions apply<h6>
							</div>
						</div>
					</div>
					<div class="item">
						<img src="img/carousel_item3.png" alt="Member"/>
						<div class="row">
							<div class="carousel-caption visible-tablet col-xs-6">
								<h2>Great Holiday Sale ----</h2>
								<h3>Save Upto 50% of hotels </h3>
								<h5>Plus Get Up to 7% Member Rewards</h5>
								<h6>* conditions apply<h6>
							</div>
						</div>
					</div>
					<div class="item">
						<img src="img/carousel_item4.png" alt="Member"/>
						<div class="row">
							<div class="carousel-caption visible-tablet col-xs-6">
								<h2>Great Holiday Sale ----</h2>
								<h3>Save Upto 50% of hotels </h3>
								<h5>Plus Get Up to 7% Member Rewards</h5>
								<h6>* conditions apply<h6>
							</div>
						</div>
					</div>
					<div class="item">
						<img src="img/carousel_item5.png" alt="Member"/>
						<div class="row">
							<div class="carousel-caption visible-tablet col-xs-6">
								<h2>Great Holiday Sale ----</h2>
								<h3>Save Upto 50% of hotels </h3>
								<h5>Plus Get Up to 7% Member Rewards</h5>
								<h6>* conditions apply<h6>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Carousel -->

			<!-- desktop banner -->
			<div id="dkt_banner" class="visible-desktop">
		
				<!-- region tabs -->
					<div id="regionTabs">
					<!-- Tabs -->
					<div class="tabbable deal-tabs" id="deal-tabs">
						<ul class="nav nav-tabs">
							<li class="active"><a href="#tab1" data-toggle="tab"  >South East Asia</a></li>
							<li><a href="#tab2" data-toggle="tab"  >North Asia</a></li>
							<li><a href="#tab3" data-toggle="tab"  >Australia</a></li>
							<li><a href="#tab4" data-toggle="tab"  >Europe &amp; US</a></li>
						</ul> 
						
					</div>	
					<div class="clearfix"></div>
		<div class="red-line"></div>
				</div>

				<!-- /region tabs -->
				
			</div>
			<!-- /desktop banner -->
			
			<!-- tablet banner -->
			<div id="tab_banner" class="visible-tablet">
				<!-- sort by options -->

				<div id="sort_by">
					<div class="row">Sort by:
						<span class="col-md-1"><a href="#" title="Best Value">Best Value</a></span>
						<span class="col-md-1"><a href="#" title="Lowest Price">Lowest Price</a></span>
						<span class="col-md-1"><a href="#" title="Distance">Distance</a></span>
						<span class="col-md-1"><a href="#" title="Star Rating">Star Rating</a></span>
						<span class="col-md-1"><a href="#" title="Reviewer Score">Reviewer Score</a></span>
					</div>
				</div>
				<!-- /sort by options -->
				
			</div>
			<!-- /tablet banner -->
			
			<!-- mobile banner -->

			<div id="mbl_banner" class="visible-phone">
			<!-- Button trigger modal -->
	

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h2 class="modal-title" id="myModalLabel">Find a hotel deal</h2>
      </div>
      <div class="modal-body">
						<form class="form-inline datepicker" method="get" name="searchBot role="form">
							<div class=" where">
								<h5>Where</h5>
								<input type="text"  class="form-control input-md" placeholder="Location.." id="locationText">
							</div>	
							<div class="checkdate form-group ">
								<h5>Check-in</h5>
								<input type="text" class="check-input form-control input-sm "  placeholder="dd/mm/yy">
							</div>
							<div class="checkdate">
								<h5>Check-out</h5>
								<input type="text" class="check-input form-control input-sm "  placeholder="dd/mm/yy">
							</div>								
							<div class="controls">
							<div class="errorMessage">&nbsp;</div>	
								<input type="button" class="btn btn-search" onclick="doSearch(this.form)" value="Search" name="search">
							</div>

							<div class=" promo-code">                        
								<p><h5>I have a promotion code</h5></p>
								<input type="text"  name="couponCode" id="couponCode" class="form-control input-md" placeholder="Location.." id="locationText">
							</div>                        
						</form>				
      </div>
   </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

				<table width="100%">
					<tr>
						<td width="50%">
							<ul class="nav">
								<li class="dropdown">
									<a class="dropdown-toggle" data-toggle="dropdown" href="#">Australia & NZ 
									<span class="caret "></span> </a>
									<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
										<li><a href="#tab1" data-toggle="tab" >South East Asia</a></li>
										<li><a href="#tab2" data-toggle="tab" >North Asia</a></li>
										<li><a href="#tab3" data-toggle="tab" >Australia & NZ</a></li>
										<li><a href="#tab4" data-toggle="tab">Europe & US</a></li>
									</ul>
								</li>
							</ul>
						</td>
						<td align="right">
								<div class="panel-group" id="accordion">
									<div class="panel">
										<div class="panel-heading">
										<a  href="#" data-toggle="modal" data-target="#myModal" >Search more hotels <span class="right-caret"></span> </a>
										</div>
									</div>
								</div>
						</td>
					</tr>
					</table>	
			</div>
					
			<!-- /mobile banner -->
		</div>
		<!-- END VIEW PARTIAL: banner.phtml -->
		
		<!-- START VIEW PARTIAL: hotel/item list -->
		<!-- Hotel List -->
				
		<div class="clearfix"></div>
		<div id="hotelList" class="subContainer">
			<div class="row">
				<div class="tab-content">
					<div class=" tab-pane active" id="tab1">
						<!--Forloop Starts--> 
															<div class="hotelDeal col-md-6" style="cursor: default;">
																<div class="row">
									<div class="image_section col-md-5" id="image_section">
										<a>
											<div >
											<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120" />
											<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
												</div>
											</div>        
										</a>					
									</div>
								
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div class="purple-color" title="Mode Sathorn Hotel">Mode Sathorn Hotel</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" >  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div class="sign-out-member-offer" style="display: none;">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
											<div class="clear"></div>
								</div>
															<div class="hotelDeal col-md-6" style="cursor: default;">
																<div class="row">
									<div class="image_section col-md-5" id="image_section">
										<a>
											<div >
											<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120" />
											<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
												</div>
											</div>        
										</a>					
									</div>
								
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div class="purple-color" title="Mode Sathorn Hotel">Mode Sathorn Hotel</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" >  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div class="sign-out-member-offer" style="display: none;">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
											<div class="clear"></div>
								</div>
															<div class="hotelDeal col-md-6" style="cursor: default;">
																<div class="row">
									<div class="image_section col-md-5" id="image_section">
										<a>
											<div >
											<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120" />
											<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
												</div>
											</div>        
										</a>					
									</div>
								
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div class="purple-color" title="Mode Sathorn Hotel">Mode Sathorn Hotel</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" >  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div class="sign-out-member-offer" style="display: none;">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
											<div class="clear"></div>
								</div>
															<div class="hotelDeal col-md-6" style="cursor: default;">
																<div class="row">
									<div class="image_section col-md-5" id="image_section">
										<a>
											<div >
											<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120" />
											<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
												</div>
											</div>        
										</a>					
									</div>
								
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div class="purple-color" title="Mode Sathorn Hotel">Mode Sathorn Hotel</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" >  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div class="sign-out-member-offer" style="display: none;">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
											<div class="clear"></div>
								</div>
															<div class="hotelDeal col-md-6" style="cursor: default;">
																<div class="row">
									<div class="image_section col-md-5" id="image_section">
										<a>
											<div >
											<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120" />
											<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
												</div>
											</div>        
										</a>					
									</div>
								
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div class="purple-color" title="Mode Sathorn Hotel">Mode Sathorn Hotel</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" >  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div class="sign-out-member-offer" style="display: none;">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
											<div class="clear"></div>
								</div>
															<div class="hotelDeal col-md-6" style="cursor: default;">
																<div class="row">
									<div class="image_section col-md-5" id="image_section">
										<a>
											<div >
											<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120" />
											<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
												</div>
											</div>        
										</a>					
									</div>
								
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div class="purple-color" title="Mode Sathorn Hotel">Mode Sathorn Hotel</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" >  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div class="sign-out-member-offer" style="display: none;">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
											<div class="clear"></div>
								</div>
															<div class="hotelDeal col-md-6" style="cursor: default;">
																<div class="row">
									<div class="image_section col-md-5" id="image_section">
										<a>
											<div >
											<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120" />
											<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
												</div>
											</div>        
										</a>					
									</div>
								
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div class="purple-color" title="Mode Sathorn Hotel">Mode Sathorn Hotel</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" >  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div class="sign-out-member-offer" style="display: none;">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
											<div class="clear"></div>
								</div>
														<!--Forloop Ends--> 
									</div>				
									
									<div class=" tab-pane" id="tab2">
									<!--Forloop Starts--> 
																			<div class="hotelDeal col-md-6" style="cursor: default;">
										<div class="row">
											<div class="image_section col-md-5" id="image_section">
												<a>
												<div>
													<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_307928.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>
													<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
														<div class="hotel-image-text">
															<div class="hotel-location">Austalia</div>
															<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
														</div>
													</div>        
												</a>
											</div>
											<div class="middle-offer-section col-md-5">
												<div class="hotelInfo">
													<h3>
													<!-- HOTEL NAME -->
														<a>
														<div class="purple-color" title="Mode Sathorn Hotel">Landmark Hotel </div>                
														</a>        
													</h3>
													<div class="campaign-promo-offer">Save 50%</div>
													<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
													<div class="members-extras-block">                
														<!-- The Big Red Plus Sign -->
														<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">  
														<div class="font_red member-extras-text">Member Extras</div>
													</div>
													<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
													<div class="sign-out-member-offer" style="display: none;">  
														<span>
															<!-- Show_JoinHotelClub_Popup()-->
															<p>Freebies Included</p>
															<p>Find out more &gt;&gt;</p>
														</span>
													</div>
												</div>
											</div>

											<div class="saveBookInfo col-md-2">
													Save<br> <span class="percentage">50%</span>
													<div class="clear"></div>
													<div class="btn button">
													<a>Book</a>
													</div><br>
													<p class="inclusions">Travel: Now - 31/12/2013</p>								
											</div>
										</div>
									<div class="clear"></div>
										</div>
																			<div class="hotelDeal col-md-6" style="cursor: default;">
										<div class="row">
											<div class="image_section col-md-5" id="image_section">
												<a>
												<div>
													<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_307928.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>
													<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
														<div class="hotel-image-text">
															<div class="hotel-location">Austalia</div>
															<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
														</div>
													</div>        
												</a>
											</div>
											<div class="middle-offer-section col-md-5">
												<div class="hotelInfo">
													<h3>
													<!-- HOTEL NAME -->
														<a>
														<div class="purple-color" title="Mode Sathorn Hotel">Landmark Hotel </div>                
														</a>        
													</h3>
													<div class="campaign-promo-offer">Save 50%</div>
													<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
													<div class="members-extras-block">                
														<!-- The Big Red Plus Sign -->
														<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">  
														<div class="font_red member-extras-text">Member Extras</div>
													</div>
													<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
													<div class="sign-out-member-offer" style="display: none;">  
														<span>
															<!-- Show_JoinHotelClub_Popup()-->
															<p>Freebies Included</p>
															<p>Find out more &gt;&gt;</p>
														</span>
													</div>
												</div>
											</div>

											<div class="saveBookInfo col-md-2">
													Save<br> <span class="percentage">50%</span>
													<div class="clear"></div>
													<div class="btn button">
													<a>Book</a>
													</div><br>
													<p class="inclusions">Travel: Now - 31/12/2013</p>								
											</div>
										</div>
									<div class="clear"></div>
										</div>
																			<div class="hotelDeal col-md-6" style="cursor: default;">
										<div class="row">
											<div class="image_section col-md-5" id="image_section">
												<a>
												<div>
													<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_307928.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>
													<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
														<div class="hotel-image-text">
															<div class="hotel-location">Austalia</div>
															<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
														</div>
													</div>        
												</a>
											</div>
											<div class="middle-offer-section col-md-5">
												<div class="hotelInfo">
													<h3>
													<!-- HOTEL NAME -->
														<a>
														<div class="purple-color" title="Mode Sathorn Hotel">Landmark Hotel </div>                
														</a>        
													</h3>
													<div class="campaign-promo-offer">Save 50%</div>
													<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
													<div class="members-extras-block">                
														<!-- The Big Red Plus Sign -->
														<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">  
														<div class="font_red member-extras-text">Member Extras</div>
													</div>
													<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
													<div class="sign-out-member-offer" style="display: none;">  
														<span>
															<!-- Show_JoinHotelClub_Popup()-->
															<p>Freebies Included</p>
															<p>Find out more &gt;&gt;</p>
														</span>
													</div>
												</div>
											</div>

											<div class="saveBookInfo col-md-2">
													Save<br> <span class="percentage">50%</span>
													<div class="clear"></div>
													<div class="btn button">
													<a>Book</a>
													</div><br>
													<p class="inclusions">Travel: Now - 31/12/2013</p>								
											</div>
										</div>
									<div class="clear"></div>
										</div>
																			<div class="hotelDeal col-md-6" style="cursor: default;">
										<div class="row">
											<div class="image_section col-md-5" id="image_section">
												<a>
												<div>
													<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_307928.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>
													<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
														<div class="hotel-image-text">
															<div class="hotel-location">Austalia</div>
															<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
														</div>
													</div>        
												</a>
											</div>
											<div class="middle-offer-section col-md-5">
												<div class="hotelInfo">
													<h3>
													<!-- HOTEL NAME -->
														<a>
														<div class="purple-color" title="Mode Sathorn Hotel">Landmark Hotel </div>                
														</a>        
													</h3>
													<div class="campaign-promo-offer">Save 50%</div>
													<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
													<div class="members-extras-block">                
														<!-- The Big Red Plus Sign -->
														<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">  
														<div class="font_red member-extras-text">Member Extras</div>
													</div>
													<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
													<div class="sign-out-member-offer" style="display: none;">  
														<span>
															<!-- Show_JoinHotelClub_Popup()-->
															<p>Freebies Included</p>
															<p>Find out more &gt;&gt;</p>
														</span>
													</div>
												</div>
											</div>

											<div class="saveBookInfo col-md-2">
													Save<br> <span class="percentage">50%</span>
													<div class="clear"></div>
													<div class="btn button">
													<a>Book</a>
													</div><br>
													<p class="inclusions">Travel: Now - 31/12/2013</p>								
											</div>
										</div>
									<div class="clear"></div>
										</div>
																			<div class="hotelDeal col-md-6" style="cursor: default;">
										<div class="row">
											<div class="image_section col-md-5" id="image_section">
												<a>
												<div>
													<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_307928.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>
													<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
														<div class="hotel-image-text">
															<div class="hotel-location">Austalia</div>
															<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
														</div>
													</div>        
												</a>
											</div>
											<div class="middle-offer-section col-md-5">
												<div class="hotelInfo">
													<h3>
													<!-- HOTEL NAME -->
														<a>
														<div class="purple-color" title="Mode Sathorn Hotel">Landmark Hotel </div>                
														</a>        
													</h3>
													<div class="campaign-promo-offer">Save 50%</div>
													<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
													<div class="members-extras-block">                
														<!-- The Big Red Plus Sign -->
														<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">  
														<div class="font_red member-extras-text">Member Extras</div>
													</div>
													<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
													<div class="sign-out-member-offer" style="display: none;">  
														<span>
															<!-- Show_JoinHotelClub_Popup()-->
															<p>Freebies Included</p>
															<p>Find out more &gt;&gt;</p>
														</span>
													</div>
												</div>
											</div>

											<div class="saveBookInfo col-md-2">
													Save<br> <span class="percentage">50%</span>
													<div class="clear"></div>
													<div class="btn button">
													<a>Book</a>
													</div><br>
													<p class="inclusions">Travel: Now - 31/12/2013</p>								
											</div>
										</div>
									<div class="clear"></div>
										</div>
																			<div class="hotelDeal col-md-6" style="cursor: default;">
										<div class="row">
											<div class="image_section col-md-5" id="image_section">
												<a>
												<div>
													<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_307928.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>
													<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
														<div class="hotel-image-text">
															<div class="hotel-location">Austalia</div>
															<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
														</div>
													</div>        
												</a>
											</div>
											<div class="middle-offer-section col-md-5">
												<div class="hotelInfo">
													<h3>
													<!-- HOTEL NAME -->
														<a>
														<div class="purple-color" title="Mode Sathorn Hotel">Landmark Hotel </div>                
														</a>        
													</h3>
													<div class="campaign-promo-offer">Save 50%</div>
													<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
													<div class="members-extras-block">                
														<!-- The Big Red Plus Sign -->
														<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">  
														<div class="font_red member-extras-text">Member Extras</div>
													</div>
													<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
													<div class="sign-out-member-offer" style="display: none;">  
														<span>
															<!-- Show_JoinHotelClub_Popup()-->
															<p>Freebies Included</p>
															<p>Find out more &gt;&gt;</p>
														</span>
													</div>
												</div>
											</div>

											<div class="saveBookInfo col-md-2">
													Save<br> <span class="percentage">50%</span>
													<div class="clear"></div>
													<div class="btn button">
													<a>Book</a>
													</div><br>
													<p class="inclusions">Travel: Now - 31/12/2013</p>								
											</div>
										</div>
									<div class="clear"></div>
										</div>
																			<div class="hotelDeal col-md-6" style="cursor: default;">
										<div class="row">
											<div class="image_section col-md-5" id="image_section">
												<a>
												<div>
													<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_307928.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>
													<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
														<div class="hotel-image-text">
															<div class="hotel-location">Austalia</div>
															<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
														</div>
													</div>        
												</a>
											</div>
											<div class="middle-offer-section col-md-5">
												<div class="hotelInfo">
													<h3>
													<!-- HOTEL NAME -->
														<a>
														<div class="purple-color" title="Mode Sathorn Hotel">Landmark Hotel </div>                
														</a>        
													</h3>
													<div class="campaign-promo-offer">Save 50%</div>
													<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
													<div class="members-extras-block">                
														<!-- The Big Red Plus Sign -->
														<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">  
														<div class="font_red member-extras-text">Member Extras</div>
													</div>
													<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
													<div class="sign-out-member-offer" style="display: none;">  
														<span>
															<!-- Show_JoinHotelClub_Popup()-->
															<p>Freebies Included</p>
															<p>Find out more &gt;&gt;</p>
														</span>
													</div>
												</div>
											</div>

											<div class="saveBookInfo col-md-2">
													Save<br> <span class="percentage">50%</span>
													<div class="clear"></div>
													<div class="btn button">
													<a>Book</a>
													</div><br>
													<p class="inclusions">Travel: Now - 31/12/2013</p>								
											</div>
										</div>
									<div class="clear"></div>
										</div>
																		<!--Forloop Ends--> 
									</div>

									<div class=" tab-pane" id="tab3">
										<!--Forloop Starts--> 
															<div class="hotelDeal col-md-6" style="cursor: default;">
								 <div class="row">
									<div class="image_section col-md-5" id="image_section">
										<a>
											<div>
											<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_316563.jpg" class="img-responsive"  alt="Responsive image" id="image_hotel" width="180" height="120"/>					
												<div class="hotel-image-text">
													<div class="hotel-location">UK</div>
													<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div class="purple-color" title="Mode Sathorn Hotel">Jupiters Hotel and ...</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div class="sign-out-member-offer" style="display: none;">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a >Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>						
									</div>
								 </div>	
							<div class="clear"></div>
								</div>
															<div class="hotelDeal col-md-6" style="cursor: default;">
								 <div class="row">
									<div class="image_section col-md-5" id="image_section">
										<a>
											<div>
											<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_316563.jpg" class="img-responsive"  alt="Responsive image" id="image_hotel" width="180" height="120"/>					
												<div class="hotel-image-text">
													<div class="hotel-location">UK</div>
													<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div class="purple-color" title="Mode Sathorn Hotel">Jupiters Hotel and ...</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div class="sign-out-member-offer" style="display: none;">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a >Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>						
									</div>
								 </div>	
							<div class="clear"></div>
								</div>
															<div class="hotelDeal col-md-6" style="cursor: default;">
								 <div class="row">
									<div class="image_section col-md-5" id="image_section">
										<a>
											<div>
											<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_316563.jpg" class="img-responsive"  alt="Responsive image" id="image_hotel" width="180" height="120"/>					
												<div class="hotel-image-text">
													<div class="hotel-location">UK</div>
													<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div class="purple-color" title="Mode Sathorn Hotel">Jupiters Hotel and ...</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div class="sign-out-member-offer" style="display: none;">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a >Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>						
									</div>
								 </div>	
							<div class="clear"></div>
								</div>
															<div class="hotelDeal col-md-6" style="cursor: default;">
								 <div class="row">
									<div class="image_section col-md-5" id="image_section">
										<a>
											<div>
											<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_316563.jpg" class="img-responsive"  alt="Responsive image" id="image_hotel" width="180" height="120"/>					
												<div class="hotel-image-text">
													<div class="hotel-location">UK</div>
													<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div class="purple-color" title="Mode Sathorn Hotel">Jupiters Hotel and ...</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div class="sign-out-member-offer" style="display: none;">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a >Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>						
									</div>
								 </div>	
							<div class="clear"></div>
								</div>
															<div class="hotelDeal col-md-6" style="cursor: default;">
								 <div class="row">
									<div class="image_section col-md-5" id="image_section">
										<a>
											<div>
											<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_316563.jpg" class="img-responsive"  alt="Responsive image" id="image_hotel" width="180" height="120"/>					
												<div class="hotel-image-text">
													<div class="hotel-location">UK</div>
													<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div class="purple-color" title="Mode Sathorn Hotel">Jupiters Hotel and ...</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div class="sign-out-member-offer" style="display: none;">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a >Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>						
									</div>
								 </div>	
							<div class="clear"></div>
								</div>
															<div class="hotelDeal col-md-6" style="cursor: default;">
								 <div class="row">
									<div class="image_section col-md-5" id="image_section">
										<a>
											<div>
											<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_316563.jpg" class="img-responsive"  alt="Responsive image" id="image_hotel" width="180" height="120"/>					
												<div class="hotel-image-text">
													<div class="hotel-location">UK</div>
													<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div class="purple-color" title="Mode Sathorn Hotel">Jupiters Hotel and ...</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div class="sign-out-member-offer" style="display: none;">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a >Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>						
									</div>
								 </div>	
							<div class="clear"></div>
								</div>
															<div class="hotelDeal col-md-6" style="cursor: default;">
								 <div class="row">
									<div class="image_section col-md-5" id="image_section">
										<a>
											<div>
											<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_316563.jpg" class="img-responsive"  alt="Responsive image" id="image_hotel" width="180" height="120"/>					
												<div class="hotel-image-text">
													<div class="hotel-location">UK</div>
													<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div class="purple-color" title="Mode Sathorn Hotel">Jupiters Hotel and ...</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div class="sign-out-member-offer" style="display: none;">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a >Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>						
									</div>
								 </div>	
							<div class="clear"></div>
								</div>
														<!--Forloop Ends--> 
									</div>
									<div class="tab-pane" id="tab4">
										<!--Forloop Starts--> 
															<div class="hotelDeal col-md-6" style="cursor: default;">
								 <div class="row">
									<div class="image_section col-md-5" id="image_section">
										<a>
											<div>
											<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_23106.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>	
											<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
												<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a href="javascript:void(0);">
												<div class="purple-color" title="Mode Sathorn Hotel">Villa Alessandra</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div class="sign-out-member-offer" style="display: none;">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
							<div class="clear"></div>
								</div>
															<div class="hotelDeal col-md-6" style="cursor: default;">
								 <div class="row">
									<div class="image_section col-md-5" id="image_section">
										<a>
											<div>
											<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_23106.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>	
											<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
												<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a href="javascript:void(0);">
												<div class="purple-color" title="Mode Sathorn Hotel">Villa Alessandra</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div class="sign-out-member-offer" style="display: none;">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
							<div class="clear"></div>
								</div>
															<div class="hotelDeal col-md-6" style="cursor: default;">
								 <div class="row">
									<div class="image_section col-md-5" id="image_section">
										<a>
											<div>
											<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_23106.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>	
											<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
												<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a href="javascript:void(0);">
												<div class="purple-color" title="Mode Sathorn Hotel">Villa Alessandra</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div class="sign-out-member-offer" style="display: none;">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
							<div class="clear"></div>
								</div>
															<div class="hotelDeal col-md-6" style="cursor: default;">
								 <div class="row">
									<div class="image_section col-md-5" id="image_section">
										<a>
											<div>
											<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_23106.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>	
											<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
												<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a href="javascript:void(0);">
												<div class="purple-color" title="Mode Sathorn Hotel">Villa Alessandra</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div class="sign-out-member-offer" style="display: none;">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
							<div class="clear"></div>
								</div>
															<div class="hotelDeal col-md-6" style="cursor: default;">
								 <div class="row">
									<div class="image_section col-md-5" id="image_section">
										<a>
											<div>
											<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_23106.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>	
											<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
												<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a href="javascript:void(0);">
												<div class="purple-color" title="Mode Sathorn Hotel">Villa Alessandra</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div class="sign-out-member-offer" style="display: none;">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
							<div class="clear"></div>
								</div>
															<div class="hotelDeal col-md-6" style="cursor: default;">
								 <div class="row">
									<div class="image_section col-md-5" id="image_section">
										<a>
											<div>
											<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_23106.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>	
											<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
												<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a href="javascript:void(0);">
												<div class="purple-color" title="Mode Sathorn Hotel">Villa Alessandra</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div class="sign-out-member-offer" style="display: none;">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
							<div class="clear"></div>
								</div>
															<div class="hotelDeal col-md-6" style="cursor: default;">
								 <div class="row">
									<div class="image_section col-md-5" id="image_section">
										<a>
											<div>
											<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_23106.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>	
											<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
												<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a href="javascript:void(0);">
												<div class="purple-color" title="Mode Sathorn Hotel">Villa Alessandra</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div class="sign-out-member-offer" style="display: none;">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
							<div class="clear"></div>
								</div>
										<!--Forloop Ends--> 
					</div>
					</div>
			</div>
		</div>
				<!-- /Hotel List -->
	
		<!-- END VIEW PARTIAL: hotel/item list -->
	</div>
	
	<!-- include external js -->
	<script src="http://code.jquery.com/jquery.js"></script>
	<script src="bootstrap/js/bootstrap.min.js"></script>
	<!-- /include external js -->
</body>
</html>
