<html lang="en"><head>
	<meta charset="utf-8">
	<title>Hotel Club - Great Holidays - Banner</title>
	<meta content="width=device-width, initial-scale=1.0" name="viewport">
	<!-- include bootstrap -->
	<link rel="stylesheet" href="bootstrap/css/bootstrap-responsive.css">
	<link media="screen" rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
	<link media="screen" rel="stylesheet" href="css/hc_great_holidays.css">
</head>
<body>
	<div class="container">
		
		<!-- START VIEW PARTIAL: banner.phtml -->
		<div class="subContainer" id="banner">
				<!-- Desktop Search Widget -->
				<div class="clearfix"></div>
					<div class="visible-desktop" id="dkt_searchBot">
						<!-- search -->
						<form form"="" name="searchBot role=" method="get" class="form-inline datepicker">
							<div class=" where">
								<h2>Find a hotel deal</h2>
								<p>Where</p>
								<input type="text" id="locationText" placeholder="Location.." class="form-control input-md">
							</div>	
							<div class="form-group ">
								<p>Check-in</p>
								<input type="text" placeholder="dd/mm/yy" class="form-control input-sm">
							</div>
							<div class="form-group ">
								<p>Check-out</p>
								<input type="text" placeholder="dd/mm/yy" class="form-control input-sm ">
							</div>								
							<div class="controls">
							<div class="errorMessage">&nbsp;</div>	
								<input type="button" name="search" value="Search" onclick="doSearch(this.form)" class="btn btn-default col-md-offset-8">
							</div>
							<div class=" promo-code">                        
								<p>I have a promotion code</p>
								<input type="text" placeholder="Location.." class="form-control input-md" id="couponCode" name="couponCode">
							</div> 
							<div class="search_contacts row">
							<div class="glyphicon glyphicon-earphone col-md-1">
							</div>
							<div class=" help col-md-8">
							<p>Need Help to book ?</p>
							<p>1300 854 585 </p>
							</div>
							</div>
						</form>					
					</div>
				
				<!-- /Desktop Search Widget -->
				<!-- Tablet search widget -->
				<div class="visible-tablet" id="tbt_searchBot">
						<!-- search -->
						<form form"="" name="searchBot role=" method="get" class="form-inline datepicker">
							<div class=" where">
								<h2>Find a hotel deal</h2>
								<p>Where</p>
								<input type="text" id="locationText" placeholder="Location.." class="form-control input-md">
							</div>	
							<div class="form-group ">
								<p>Check-in</p>
								<input type="text" placeholder="dd/mm/yy" class="form-control input-sm">
							</div>
							<div class="form-group ">
								<p>Check-out</p>
								<input type="text" placeholder="dd/mm/yy" class="form-control input-sm ">
							</div>								
							<div class="controls">
							<div class="errorMessage">&nbsp;</div>	
								<input type="button" name="search" value="Search" onclick="doSearch(this.form)" class="btn btn-default col-md-offset-8">
							</div>
							<div class=" promo-code">                        
								<p>I have a promotion code</p>
								<input type="text" placeholder="Location.." class="form-control input-md" id="couponCode" name="couponCode">
							</div> 
							
						</form>					
					</div>
			<!-- /Tablet search widget -->
			<!-- carousel -->
			<div data-interval="2500" data-ride="carousel" class="carousel slide" id="dkt_carousel">
				<ol class="carousel-indicators">
					<li class="" data-slide-to="0" data-target="#dkt_carousel"></li>
					<li data-slide-to="1" data-target="#dkt_carousel" class=""></li>
					<li data-slide-to="2" data-target="#dkt_carousel"></li>
				</ol>
				<!-- Carousel items -->
				<div class="carousel-inner">
					<div class="item">
						<img alt="Member" src="img/carousel_item1.png">
						<div class="row">
							<div class="carousel-caption visible-tablet col-md-offset-3">
								<h2>Great Holiday Sale ----</h2>
								<h3>Save Upto 50% of hotels </h3>
								<h5>Plus Get Up to 7% Member Rewards</h5>
								<h6>* conditions apply</h6><h6>
							</h6></div>
						</div>
					</div>
					<div class="item active left">
						<img alt="Member" src="img/carousel_item2.png">
						<div class="row">
							<div class="carousel-caption visible-tablet col-xs-6">
								<h2>Great Holiday Sale ----</h2>
								<h3>Save Upto 50% of hotels </h3>
								<h5>Plus Get Up to 7% Member Rewards</h5>
								<h6>* conditions apply</h6><h6>
							</h6></div>
						</div>
					</div>
					<div class="item next left">
						<img alt="Member" src="img/carousel_item3.png">
						<div class="row">
							<div class="carousel-caption visible-tablet col-xs-6">
								<h2>Great Holiday Sale ----</h2>
								<h3>Save Upto 50% of hotels </h3>
								<h5>Plus Get Up to 7% Member Rewards</h5>
								<h6>* conditions apply</h6><h6>
							</h6></div>
						</div>
					</div>
					<div class="item">
						<img alt="Member" src="img/carousel_item4.png">
						<div class="row">
							<div class="carousel-caption visible-tablet col-xs-6">
								<h2>Great Holiday Sale ----</h2>
								<h3>Save Upto 50% of hotels </h3>
								<h5>Plus Get Up to 7% Member Rewards</h5>
								<h6>* conditions apply</h6><h6>
							</h6></div>
						</div>
					</div>
					<div class="item">
						<img alt="Member" src="img/carousel_item5.png">
						<div class="row">
							<div class="carousel-caption visible-tablet col-xs-6">
								<h2>Great Holiday Sale ----</h2>
								<h3>Save Upto 50% of hotels </h3>
								<h5>Plus Get Up to 7% Member Rewards</h5>
								<h6>* conditions apply</h6><h6>
							</h6></div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Carousel -->

			<!-- desktop banner -->
			<div class="visible-desktop" id="dkt_banner">
		
				<!-- region tabs -->
					<div id="regionTabs">
					<!-- Tabs -->
					<div id="deal-tabs" class="tabbable deal-tabs">
						<ul class="nav nav-tabs">
							<li class="active"><a data-toggle="tab" href="#tab1">South East Asia</a></li>
							<li><a data-toggle="tab" href="#tab2">North Asia</a></li>
							<li><a data-toggle="tab" href="#tab3">Australia</a></li>
							<li><a data-toggle="tab" href="#tab4">Europe &amp; US</a></li>
						</ul> 
						
					</div>	
					<div class="clearfix"></div>
		<div class="red-line"></div>
				</div>

				<!-- /region tabs -->
				
			</div>
			<!-- /desktop banner -->
			
			<!-- tablet banner -->
			<div class="visible-tablet" id="tab_banner">
				<!-- sort by options -->

				<div id="sort_by">
					<div class="row">Sort by:
						<span class="col-md-1"><a title="Best Value" href="#">Best Value</a></span>
						<span class="col-md-1"><a title="Lowest Price" href="#">Lowest Price</a></span>
						<span class="col-md-1"><a title="Distance" href="#">Distance</a></span>
						<span class="col-md-1"><a title="Star Rating" href="#">Star Rating</a></span>
						<span class="col-md-1"><a title="Reviewer Score" href="#">Reviewer Score</a></span>
					</div>
				</div>
				<!-- /sort by options -->
				
			</div>
			<!-- /tablet banner -->
			
			<!-- mobile banner -->

			<div class="visible-phone" id="mbl_banner">
			<!-- Button trigger modal -->
	

<!-- Modal -->
<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
        <h2 id="myModalLabel" class="modal-title">Find a hotel deal</h2>
      </div>
      <div class="modal-body">
						<form form"="" name="searchBot role=" method="get" class="form-inline datepicker">
							<div class=" where">
								<h5>Where</h5>
								<input type="text" id="locationText" placeholder="Location.." class="form-control input-md">
							</div>	
							<div class="checkdate form-group ">
								<h5>Check-in</h5>
								<input type="text" placeholder="dd/mm/yy" class="check-input form-control input-sm ">
							</div>
							<div class="checkdate">
								<h5>Check-out</h5>
								<input type="text" placeholder="dd/mm/yy" class="check-input form-control input-sm ">
							</div>								
							<div class="controls">
							<div class="errorMessage">&nbsp;</div>	
								<input type="button" name="search" value="Search" onclick="doSearch(this.form)" class="btn btn-search">
							</div>

							<div class=" promo-code">                        
								<p></p><h5>I have a promotion code</h5><p></p>
								<input type="text" placeholder="Location.." class="form-control input-md" id="couponCode" name="couponCode">
							</div>                        
						</form>				
      </div>
   </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

				<table width="100%">
					<tbody><tr>
						<td width="50%">
							<ul class="nav">
								<li class="dropdown">
									<a href="#" data-toggle="dropdown" class="dropdown-toggle">Australia &amp; NZ 
									<span class="caret "></span> </a>
									<ul aria-labelledby="dLabel" role="menu" class="dropdown-menu">
										<li><a data-toggle="tab" href="#tab1">South East Asia</a></li>
										<li><a data-toggle="tab" href="#tab2">North Asia</a></li>
										<li><a data-toggle="tab" href="#tab3">Australia &amp; NZ</a></li>
										<li><a data-toggle="tab" href="#tab4">Europe &amp; US</a></li>
									</ul>
								</li>
							</ul>
						</td>
						<td align="right">
								<div id="accordion" class="panel-group">
									<div class="panel">
										<div class="panel-heading">
										<a data-target="#myModal" data-toggle="modal" href="#">Search more hotels <span class="right-caret"></span> </a>
										</div>
									</div>
								</div>
						</td>
					</tr>
					</tbody></table>	
			</div>
					
			<!-- /mobile banner -->
		</div>
		<!-- END VIEW PARTIAL: banner.phtml -->
		
		<!-- START VIEW PARTIAL: hotel/item list -->
		<!-- Hotel List -->
				
		<div class="clearfix"></div>
		<div class="subContainer" id="hotelList">
			<div class="row">
				<div class="tab-content">
					<div id="tab1" class=" tab-pane active">
						<!--Forloop Starts--> 
															<div style="cursor: default;" class="hotelDeal col-md-6">
																<div class="row">
									<div id="image_section" class="image_section col-md-5">
										<a>
											<div>
											<img width="180" height="120" alt="Responsive image" id="image_hotel" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg">
											<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
												</div>
											</div>        
										</a>					
									</div>
								
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div title="Mode Sathorn Hotel" class="purple-color">Mode Sathorn Hotel</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div style="display: none;" class="sign-out-member-offer">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
											<div class="clear"></div>
								</div>
															<div style="cursor: default;" class="hotelDeal col-md-6">
																<div class="row">
									<div id="image_section" class="image_section col-md-5">
										<a>
											<div>
											<img width="180" height="120" alt="Responsive image" id="image_hotel" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg">
											<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
												</div>
											</div>        
										</a>					
									</div>
								
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div title="Mode Sathorn Hotel" class="purple-color">Mode Sathorn Hotel</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div style="display: none;" class="sign-out-member-offer">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
											<div class="clear"></div>
								</div>
															<div style="cursor: default;" class="hotelDeal col-md-6">
																<div class="row">
									<div id="image_section" class="image_section col-md-5">
										<a>
											<div>
											<img width="180" height="120" alt="Responsive image" id="image_hotel" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg">
											<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
												</div>
											</div>        
										</a>					
									</div>
								
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div title="Mode Sathorn Hotel" class="purple-color">Mode Sathorn Hotel</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div style="display: none;" class="sign-out-member-offer">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
											<div class="clear"></div>
								</div>
															<div style="cursor: default;" class="hotelDeal col-md-6">
																<div class="row">
									<div id="image_section" class="image_section col-md-5">
										<a>
											<div>
											<img width="180" height="120" alt="Responsive image" id="image_hotel" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg">
											<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
												</div>
											</div>        
										</a>					
									</div>
								
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div title="Mode Sathorn Hotel" class="purple-color">Mode Sathorn Hotel</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div style="display: none;" class="sign-out-member-offer">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
											<div class="clear"></div>
								</div>
															<div style="cursor: default;" class="hotelDeal col-md-6">
																<div class="row">
									<div id="image_section" class="image_section col-md-5">
										<a>
											<div>
											<img width="180" height="120" alt="Responsive image" id="image_hotel" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg">
											<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
												</div>
											</div>        
										</a>					
									</div>
								
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div title="Mode Sathorn Hotel" class="purple-color">Mode Sathorn Hotel</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div style="display: none;" class="sign-out-member-offer">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
											<div class="clear"></div>
								</div>
															<div style="cursor: default;" class="hotelDeal col-md-6">
																<div class="row">
									<div id="image_section" class="image_section col-md-5">
										<a>
											<div>
											<img width="180" height="120" alt="Responsive image" id="image_hotel" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg">
											<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
												</div>
											</div>        
										</a>					
									</div>
								
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div title="Mode Sathorn Hotel" class="purple-color">Mode Sathorn Hotel</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div style="display: none;" class="sign-out-member-offer">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
											<div class="clear"></div>
								</div>
															<div style="cursor: default;" class="hotelDeal col-md-6">
																<div class="row">
									<div id="image_section" class="image_section col-md-5">
										<a>
											<div>
											<img width="180" height="120" alt="Responsive image" id="image_hotel" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg">
											<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
												</div>
											</div>        
										</a>					
									</div>
								
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div title="Mode Sathorn Hotel" class="purple-color">Mode Sathorn Hotel</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div style="display: none;" class="sign-out-member-offer">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
											<div class="clear"></div>
								</div>
														<!--Forloop Ends--> 
									</div>				
									
									<div id="tab2" class=" tab-pane">
									<!--Forloop Starts--> 
																			<div style="cursor: default;" class="hotelDeal col-md-6">
										<div class="row">
											<div id="image_section" class="image_section col-md-5">
												<a>
												<div>
													<img width="180" height="120" alt="Responsive image" id="image_hotel" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_307928.jpg">
													<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
														<div class="hotel-image-text">
															<div class="hotel-location">Austalia</div>
															<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
														</div>
													</div>        
												</a>
											</div>
											<div class="middle-offer-section col-md-5">
												<div class="hotelInfo">
													<h3>
													<!-- HOTEL NAME -->
														<a>
														<div title="Mode Sathorn Hotel" class="purple-color">Landmark Hotel </div>                
														</a>        
													</h3>
													<div class="campaign-promo-offer">Save 50%</div>
													<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
													<div class="members-extras-block">                
														<!-- The Big Red Plus Sign -->
														<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
														<div class="font_red member-extras-text">Member Extras</div>
													</div>
													<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
													<div style="display: none;" class="sign-out-member-offer">  
														<span>
															<!-- Show_JoinHotelClub_Popup()-->
															<p>Freebies Included</p>
															<p>Find out more &gt;&gt;</p>
														</span>
													</div>
												</div>
											</div>

											<div class="saveBookInfo col-md-2">
													Save<br> <span class="percentage">50%</span>
													<div class="clear"></div>
													<div class="btn button">
													<a>Book</a>
													</div><br>
													<p class="inclusions">Travel: Now - 31/12/2013</p>								
											</div>
										</div>
									<div class="clear"></div>
										</div>
																			<div style="cursor: default;" class="hotelDeal col-md-6">
										<div class="row">
											<div id="image_section" class="image_section col-md-5">
												<a>
												<div>
													<img width="180" height="120" alt="Responsive image" id="image_hotel" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_307928.jpg">
													<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
														<div class="hotel-image-text">
															<div class="hotel-location">Austalia</div>
															<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
														</div>
													</div>        
												</a>
											</div>
											<div class="middle-offer-section col-md-5">
												<div class="hotelInfo">
													<h3>
													<!-- HOTEL NAME -->
														<a>
														<div title="Mode Sathorn Hotel" class="purple-color">Landmark Hotel </div>                
														</a>        
													</h3>
													<div class="campaign-promo-offer">Save 50%</div>
													<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
													<div class="members-extras-block">                
														<!-- The Big Red Plus Sign -->
														<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
														<div class="font_red member-extras-text">Member Extras</div>
													</div>
													<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
													<div style="display: none;" class="sign-out-member-offer">  
														<span>
															<!-- Show_JoinHotelClub_Popup()-->
															<p>Freebies Included</p>
															<p>Find out more &gt;&gt;</p>
														</span>
													</div>
												</div>
											</div>

											<div class="saveBookInfo col-md-2">
													Save<br> <span class="percentage">50%</span>
													<div class="clear"></div>
													<div class="btn button">
													<a>Book</a>
													</div><br>
													<p class="inclusions">Travel: Now - 31/12/2013</p>								
											</div>
										</div>
									<div class="clear"></div>
										</div>
																			<div style="cursor: default;" class="hotelDeal col-md-6">
										<div class="row">
											<div id="image_section" class="image_section col-md-5">
												<a>
												<div>
													<img width="180" height="120" alt="Responsive image" id="image_hotel" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_307928.jpg">
													<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
														<div class="hotel-image-text">
															<div class="hotel-location">Austalia</div>
															<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
														</div>
													</div>        
												</a>
											</div>
											<div class="middle-offer-section col-md-5">
												<div class="hotelInfo">
													<h3>
													<!-- HOTEL NAME -->
														<a>
														<div title="Mode Sathorn Hotel" class="purple-color">Landmark Hotel </div>                
														</a>        
													</h3>
													<div class="campaign-promo-offer">Save 50%</div>
													<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
													<div class="members-extras-block">                
														<!-- The Big Red Plus Sign -->
														<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
														<div class="font_red member-extras-text">Member Extras</div>
													</div>
													<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
													<div style="display: none;" class="sign-out-member-offer">  
														<span>
															<!-- Show_JoinHotelClub_Popup()-->
															<p>Freebies Included</p>
															<p>Find out more &gt;&gt;</p>
														</span>
													</div>
												</div>
											</div>

											<div class="saveBookInfo col-md-2">
													Save<br> <span class="percentage">50%</span>
													<div class="clear"></div>
													<div class="btn button">
													<a>Book</a>
													</div><br>
													<p class="inclusions">Travel: Now - 31/12/2013</p>								
											</div>
										</div>
									<div class="clear"></div>
										</div>
																			<div style="cursor: default;" class="hotelDeal col-md-6">
										<div class="row">
											<div id="image_section" class="image_section col-md-5">
												<a>
												<div>
													<img width="180" height="120" alt="Responsive image" id="image_hotel" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_307928.jpg">
													<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
														<div class="hotel-image-text">
															<div class="hotel-location">Austalia</div>
															<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
														</div>
													</div>        
												</a>
											</div>
											<div class="middle-offer-section col-md-5">
												<div class="hotelInfo">
													<h3>
													<!-- HOTEL NAME -->
														<a>
														<div title="Mode Sathorn Hotel" class="purple-color">Landmark Hotel </div>                
														</a>        
													</h3>
													<div class="campaign-promo-offer">Save 50%</div>
													<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
													<div class="members-extras-block">                
														<!-- The Big Red Plus Sign -->
														<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
														<div class="font_red member-extras-text">Member Extras</div>
													</div>
													<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
													<div style="display: none;" class="sign-out-member-offer">  
														<span>
															<!-- Show_JoinHotelClub_Popup()-->
															<p>Freebies Included</p>
															<p>Find out more &gt;&gt;</p>
														</span>
													</div>
												</div>
											</div>

											<div class="saveBookInfo col-md-2">
													Save<br> <span class="percentage">50%</span>
													<div class="clear"></div>
													<div class="btn button">
													<a>Book</a>
													</div><br>
													<p class="inclusions">Travel: Now - 31/12/2013</p>								
											</div>
										</div>
									<div class="clear"></div>
										</div>
																			<div style="cursor: default;" class="hotelDeal col-md-6">
										<div class="row">
											<div id="image_section" class="image_section col-md-5">
												<a>
												<div>
													<img width="180" height="120" alt="Responsive image" id="image_hotel" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_307928.jpg">
													<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
														<div class="hotel-image-text">
															<div class="hotel-location">Austalia</div>
															<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
														</div>
													</div>        
												</a>
											</div>
											<div class="middle-offer-section col-md-5">
												<div class="hotelInfo">
													<h3>
													<!-- HOTEL NAME -->
														<a>
														<div title="Mode Sathorn Hotel" class="purple-color">Landmark Hotel </div>                
														</a>        
													</h3>
													<div class="campaign-promo-offer">Save 50%</div>
													<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
													<div class="members-extras-block">                
														<!-- The Big Red Plus Sign -->
														<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
														<div class="font_red member-extras-text">Member Extras</div>
													</div>
													<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
													<div style="display: none;" class="sign-out-member-offer">  
														<span>
															<!-- Show_JoinHotelClub_Popup()-->
															<p>Freebies Included</p>
															<p>Find out more &gt;&gt;</p>
														</span>
													</div>
												</div>
											</div>

											<div class="saveBookInfo col-md-2">
													Save<br> <span class="percentage">50%</span>
													<div class="clear"></div>
													<div class="btn button">
													<a>Book</a>
													</div><br>
													<p class="inclusions">Travel: Now - 31/12/2013</p>								
											</div>
										</div>
									<div class="clear"></div>
										</div>
																			<div style="cursor: default;" class="hotelDeal col-md-6">
										<div class="row">
											<div id="image_section" class="image_section col-md-5">
												<a>
												<div>
													<img width="180" height="120" alt="Responsive image" id="image_hotel" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_307928.jpg">
													<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
														<div class="hotel-image-text">
															<div class="hotel-location">Austalia</div>
															<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
														</div>
													</div>        
												</a>
											</div>
											<div class="middle-offer-section col-md-5">
												<div class="hotelInfo">
													<h3>
													<!-- HOTEL NAME -->
														<a>
														<div title="Mode Sathorn Hotel" class="purple-color">Landmark Hotel </div>                
														</a>        
													</h3>
													<div class="campaign-promo-offer">Save 50%</div>
													<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
													<div class="members-extras-block">                
														<!-- The Big Red Plus Sign -->
														<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
														<div class="font_red member-extras-text">Member Extras</div>
													</div>
													<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
													<div style="display: none;" class="sign-out-member-offer">  
														<span>
															<!-- Show_JoinHotelClub_Popup()-->
															<p>Freebies Included</p>
															<p>Find out more &gt;&gt;</p>
														</span>
													</div>
												</div>
											</div>

											<div class="saveBookInfo col-md-2">
													Save<br> <span class="percentage">50%</span>
													<div class="clear"></div>
													<div class="btn button">
													<a>Book</a>
													</div><br>
													<p class="inclusions">Travel: Now - 31/12/2013</p>								
											</div>
										</div>
									<div class="clear"></div>
										</div>
																			<div style="cursor: default;" class="hotelDeal col-md-6">
										<div class="row">
											<div id="image_section" class="image_section col-md-5">
												<a>
												<div>
													<img width="180" height="120" alt="Responsive image" id="image_hotel" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_307928.jpg">
													<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
														<div class="hotel-image-text">
															<div class="hotel-location">Austalia</div>
															<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
														</div>
													</div>        
												</a>
											</div>
											<div class="middle-offer-section col-md-5">
												<div class="hotelInfo">
													<h3>
													<!-- HOTEL NAME -->
														<a>
														<div title="Mode Sathorn Hotel" class="purple-color">Landmark Hotel </div>                
														</a>        
													</h3>
													<div class="campaign-promo-offer">Save 50%</div>
													<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
													<div class="members-extras-block">                
														<!-- The Big Red Plus Sign -->
														<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
														<div class="font_red member-extras-text">Member Extras</div>
													</div>
													<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
													<div style="display: none;" class="sign-out-member-offer">  
														<span>
															<!-- Show_JoinHotelClub_Popup()-->
															<p>Freebies Included</p>
															<p>Find out more &gt;&gt;</p>
														</span>
													</div>
												</div>
											</div>

											<div class="saveBookInfo col-md-2">
													Save<br> <span class="percentage">50%</span>
													<div class="clear"></div>
													<div class="btn button">
													<a>Book</a>
													</div><br>
													<p class="inclusions">Travel: Now - 31/12/2013</p>								
											</div>
										</div>
									<div class="clear"></div>
										</div>
																		<!--Forloop Ends--> 
									</div>

									<div id="tab3" class=" tab-pane">
										<!--Forloop Starts--> 
															<div style="cursor: default;" class="hotelDeal col-md-6">
								 <div class="row">
									<div id="image_section" class="image_section col-md-5">
										<a>
											<div>
											<img width="180" height="120" id="image_hotel" alt="Responsive image" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_316563.jpg">					
												<div class="hotel-image-text">
													<div class="hotel-location">UK</div>
													<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div title="Mode Sathorn Hotel" class="purple-color">Jupiters Hotel and ...</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div style="display: none;" class="sign-out-member-offer">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>						
									</div>
								 </div>	
							<div class="clear"></div>
								</div>
															<div style="cursor: default;" class="hotelDeal col-md-6">
								 <div class="row">
									<div id="image_section" class="image_section col-md-5">
										<a>
											<div>
											<img width="180" height="120" id="image_hotel" alt="Responsive image" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_316563.jpg">					
												<div class="hotel-image-text">
													<div class="hotel-location">UK</div>
													<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div title="Mode Sathorn Hotel" class="purple-color">Jupiters Hotel and ...</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div style="display: none;" class="sign-out-member-offer">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>						
									</div>
								 </div>	
							<div class="clear"></div>
								</div>
															<div style="cursor: default;" class="hotelDeal col-md-6">
								 <div class="row">
									<div id="image_section" class="image_section col-md-5">
										<a>
											<div>
											<img width="180" height="120" id="image_hotel" alt="Responsive image" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_316563.jpg">					
												<div class="hotel-image-text">
													<div class="hotel-location">UK</div>
													<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div title="Mode Sathorn Hotel" class="purple-color">Jupiters Hotel and ...</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div style="display: none;" class="sign-out-member-offer">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>						
									</div>
								 </div>	
							<div class="clear"></div>
								</div>
															<div style="cursor: default;" class="hotelDeal col-md-6">
								 <div class="row">
									<div id="image_section" class="image_section col-md-5">
										<a>
											<div>
											<img width="180" height="120" id="image_hotel" alt="Responsive image" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_316563.jpg">					
												<div class="hotel-image-text">
													<div class="hotel-location">UK</div>
													<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div title="Mode Sathorn Hotel" class="purple-color">Jupiters Hotel and ...</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div style="display: none;" class="sign-out-member-offer">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>						
									</div>
								 </div>	
							<div class="clear"></div>
								</div>
															<div style="cursor: default;" class="hotelDeal col-md-6">
								 <div class="row">
									<div id="image_section" class="image_section col-md-5">
										<a>
											<div>
											<img width="180" height="120" id="image_hotel" alt="Responsive image" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_316563.jpg">					
												<div class="hotel-image-text">
													<div class="hotel-location">UK</div>
													<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div title="Mode Sathorn Hotel" class="purple-color">Jupiters Hotel and ...</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div style="display: none;" class="sign-out-member-offer">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>						
									</div>
								 </div>	
							<div class="clear"></div>
								</div>
															<div style="cursor: default;" class="hotelDeal col-md-6">
								 <div class="row">
									<div id="image_section" class="image_section col-md-5">
										<a>
											<div>
											<img width="180" height="120" id="image_hotel" alt="Responsive image" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_316563.jpg">					
												<div class="hotel-image-text">
													<div class="hotel-location">UK</div>
													<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div title="Mode Sathorn Hotel" class="purple-color">Jupiters Hotel and ...</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div style="display: none;" class="sign-out-member-offer">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>						
									</div>
								 </div>	
							<div class="clear"></div>
								</div>
															<div style="cursor: default;" class="hotelDeal col-md-6">
								 <div class="row">
									<div id="image_section" class="image_section col-md-5">
										<a>
											<div>
											<img width="180" height="120" id="image_hotel" alt="Responsive image" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_316563.jpg">					
												<div class="hotel-image-text">
													<div class="hotel-location">UK</div>
													<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a>
												<div title="Mode Sathorn Hotel" class="purple-color">Jupiters Hotel and ...</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div style="display: none;" class="sign-out-member-offer">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>						
									</div>
								 </div>	
							<div class="clear"></div>
								</div>
														<!--Forloop Ends--> 
									</div>
									<div id="tab4" class="tab-pane">
										<!--Forloop Starts--> 
															<div style="cursor: default;" class="hotelDeal col-md-6">
								 <div class="row">
									<div id="image_section" class="image_section col-md-5">
										<a>
											<div>
											<img width="180" height="120" alt="Responsive image" id="image_hotel" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_23106.jpg">	
											<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
												<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a href="javascript:void(0);">
												<div title="Mode Sathorn Hotel" class="purple-color">Villa Alessandra</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div style="display: none;" class="sign-out-member-offer">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
							<div class="clear"></div>
								</div>
															<div style="cursor: default;" class="hotelDeal col-md-6">
								 <div class="row">
									<div id="image_section" class="image_section col-md-5">
										<a>
											<div>
											<img width="180" height="120" alt="Responsive image" id="image_hotel" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_23106.jpg">	
											<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
												<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a href="javascript:void(0);">
												<div title="Mode Sathorn Hotel" class="purple-color">Villa Alessandra</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div style="display: none;" class="sign-out-member-offer">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
							<div class="clear"></div>
								</div>
															<div style="cursor: default;" class="hotelDeal col-md-6">
								 <div class="row">
									<div id="image_section" class="image_section col-md-5">
										<a>
											<div>
											<img width="180" height="120" alt="Responsive image" id="image_hotel" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_23106.jpg">	
											<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
												<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a href="javascript:void(0);">
												<div title="Mode Sathorn Hotel" class="purple-color">Villa Alessandra</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div style="display: none;" class="sign-out-member-offer">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
							<div class="clear"></div>
								</div>
															<div style="cursor: default;" class="hotelDeal col-md-6">
								 <div class="row">
									<div id="image_section" class="image_section col-md-5">
										<a>
											<div>
											<img width="180" height="120" alt="Responsive image" id="image_hotel" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_23106.jpg">	
											<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
												<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a href="javascript:void(0);">
												<div title="Mode Sathorn Hotel" class="purple-color">Villa Alessandra</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div style="display: none;" class="sign-out-member-offer">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
							<div class="clear"></div>
								</div>
															<div style="cursor: default;" class="hotelDeal col-md-6">
								 <div class="row">
									<div id="image_section" class="image_section col-md-5">
										<a>
											<div>
											<img width="180" height="120" alt="Responsive image" id="image_hotel" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_23106.jpg">	
											<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
												<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a href="javascript:void(0);">
												<div title="Mode Sathorn Hotel" class="purple-color">Villa Alessandra</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div style="display: none;" class="sign-out-member-offer">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
							<div class="clear"></div>
								</div>
															<div style="cursor: default;" class="hotelDeal col-md-6">
								 <div class="row">
									<div id="image_section" class="image_section col-md-5">
										<a>
											<div>
											<img width="180" height="120" alt="Responsive image" id="image_hotel" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_23106.jpg">	
											<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
												<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a href="javascript:void(0);">
												<div title="Mode Sathorn Hotel" class="purple-color">Villa Alessandra</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div style="display: none;" class="sign-out-member-offer">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
							<div class="clear"></div>
								</div>
															<div style="cursor: default;" class="hotelDeal col-md-6">
								 <div class="row">
									<div id="image_section" class="image_section col-md-5">
										<a>
											<div>
											<img width="180" height="120" alt="Responsive image" id="image_hotel" class="img-responsive" src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_23106.jpg">	
											<!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
												<div class="hotel-image-text">
													<div class="hotel-location">Bangkok</div>
													<div class="star4">
													<img width="148" height="12" alt="Responsive image" id="image_hotel" class="img-responsive ce-star" src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png">
													</div>
												</div>
											</div>        
										</a>
									</div>
									<div class="middle-offer-section col-md-5">
										<div class="hotelInfo">
											<h3>
											<!-- HOTEL NAME -->
												<a href="javascript:void(0);">
												<div title="Mode Sathorn Hotel" class="purple-color">Villa Alessandra</div>                
												</a>        
											</h3>
											<div class="campaign-promo-offer">Save 50%</div>
											<input type="hidden" id="hotel_inc1_1149971" value="Save 50%">
											<div class="members-extras-block">                
												<!-- The Big Red Plus Sign -->
												<img src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" alt="Member Rewards" class="members-extras-logo img-responsive">  
												<div class="font_red member-extras-text">Member Extras</div>
											</div>
											<div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
											<div style="display: none;" class="sign-out-member-offer">  
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
											</div>
										</div>
									</div>

									<div class="saveBookInfo col-md-2">
											Save<br> <span class="percentage">50%</span>
											<div class="clear"></div>
											<div class="btn button">
											<a>Book</a>
											</div><br>
											<p class="inclusions">Travel: Now - 31/12/2013</p>
									</div>
								</div>
							<div class="clear"></div>
								</div>
										<!--Forloop Ends--> 
					</div>
					</div>
			</div>
		</div>
				<!-- /Hotel List -->
	
		<!-- END VIEW PARTIAL: hotel/item list -->
	</div>
	
	<!-- include external js -->
	<script src="http://code.jquery.com/jquery.js"></script>
	<script src="bootstrap/js/bootstrap.min.js"></script>
	<!-- /include external js -->

</body></html>
