<html lang="en"><head>
	<meta charset="utf-8">
	<title>Hotel Club - Great Holidays - Banner</title>
	<meta content="width=device-width, initial-scale=1.0" name="viewport">
	<!-- include bootstrap -->
	<link rel="stylesheet" href="bootstrap/css/bootstrap-responsive.css">
	<link media="screen" rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
	<link media="screen" rel="stylesheet" href="css/hc_great_holidays.css">
</head>
<body>
	<div class="container">
		
		<!-- START VIEW PARTIAL: banner.phtml -->
		<div class="subContainer" id="banner">
				<!-- Desktop Search Widget -->
				<div class="clearfix"></div>
					<div class="visible-desktop" id="dkt_searchBot">
						<!-- search -->
						<form form"="" name="searchBot role=" method="get" class="form-inline datepicker">
							<div class=" where">
								<h2>Find a hotel deal</h2>
								<p>Where</p>
								<input type="text" id="locationText" placeholder="Location.." class="form-control input-md">
							</div>	
							<div class="form-group ">
								<p>Check-in</p>
								<input type="text" placeholder="dd/mm/yy" class="form-control input-sm">
							</div>
							<div class="form-group ">
								<p>Check-out</p>
								<input type="text" placeholder="dd/mm/yy" class="form-control input-sm ">
							</div>								
							<div class="controls">
							<div class="errorMessage">&nbsp;</div>	
								<input type="button" name="search" value="Search" onclick="doSearch(this.form)" class="btn btn-default col-md-offset-8">
							</div>
							<div class=" promo-code">                        
								<p>I have a promotion code</p>
								<input type="text" placeholder="Location.." class="form-control input-md" id="couponCode" name="couponCode">
							</div> 
							<div class="search_contacts row">
							<div class="glyphicon glyphicon-earphone col-md-1">
							</div>
							<div class=" help col-md-8">
							<p>Need Help to book ?</p>
							<p>1300 854 585 </p>
							</div>
							</div>
						</form>					
					</div>
				
				<!-- /Desktop Search Widget -->
				<!-- Tablet search widget -->
				<div class="visible-tablet" id="tbt_searchBot">
						<!-- search -->
						<form form"="" name="searchBot role=" method="get" class="form-inline datepicker">
							<div class=" where">
								<h2>Find a hotel deal</h2>
								<p>Where</p>
								<input type="text" id="locationText" placeholder="Location.." class="form-control input-md">
							</div>	
							<div class="form-group ">
								<p>Check-in</p>
								<input type="text" placeholder="dd/mm/yy" class="form-control input-sm">
							</div>
							<div class="form-group ">
								<p>Check-out</p>
								<input type="text" placeholder="dd/mm/yy" class="form-control input-sm ">
							</div>								
							<div class="controls">
							<div class="errorMessage">&nbsp;</div>	
								<input type="button" name="search" value="Search" onclick="doSearch(this.form)" class="btn btn-default col-md-offset-8">
							</div>
							<div class=" promo-code">                        
								<p>I have a promotion code</p>
								<input type="text" placeholder="Location.." class="form-control input-md" id="couponCode" name="couponCode">
							</div> 
							
						</form>					
					</div>
			<!-- /Tablet search widget -->
			<!-- carousel -->
			<div data-interval="2500" data-ride="carousel" class="carousel slide" id="dkt_carousel">
				<ol class="carousel-indicators">
					<li class="" data-slide-to="0" data-target="#dkt_carousel"></li>
					<li data-slide-to="1" data-target="#dkt_carousel" class=""></li>
					<li data-slide-to="2" data-target="#dkt_carousel" class="active"></li>
				</ol>
				<!-- Carousel items -->
				<div class="carousel-inner">
					<div class="item">
						<img alt="Member" src="img/carousel_item1.png">
						<div class="row">
							<div class="carousel-caption visible-tablet col-md-offset-3">
								<h2>Great Holiday Sale ----</h2>
								<h3>Save Upto 50% of hotels </h3>
								<h5>Plus Get Up to 7% Member Rewards</h5>
								<h6>* conditions apply</h6><h6>
							</h6></div>
						</div>
					</div>
					<div class="item">
						<img alt="Member" src="img/carousel_item2.png">
						<div class="row">
							<div class="carousel-caption visible-tablet col-xs-6">
								<h2>Great Holiday Sale ----</h2>
								<h3>Save Upto 50% of hotels </h3>
								<h5>Plus Get Up to 7% Member Rewards</h5>
								<h6>* conditions apply</h6><h6>
							</h6></div>
						</div>
					</div>
					<div class="item active">
						<img alt="Member" src="img/carousel_item3.png">
						<div class="row">
							<div class="carousel-caption visible-tablet col-xs-6">
								<h2>Great Holiday Sale ----</h2>
								<h3>Save Upto 50% of hotels </h3>
								<h5>Plus Get Up to 7% Member Rewards</h5>
								<h6>* conditions apply</h6><h6>
							</h6></div>
						</div>
					</div>
					<div class="item">
						<img alt="Member" src="img/carousel_item4.png">
						<div class="row">
							<div class="carousel-caption visible-tablet col-xs-6">
								<h2>Great Holiday Sale ----</h2>
								<h3>Save Upto 50% of hotels </h3>
								<h5>Plus Get Up to 7% Member Rewards</h5>
								<h6>* conditions apply</h6><h6>
							</h6></div>
						</div>
					</div>
					<div class="item">
						<img alt="Member" src="img/carousel_item5.png">
						<div class="row">
							<div class="carousel-caption visible-tablet col-xs-6">
								<h2>Great Holiday Sale ----</h2>
								<h3>Save Upto 50% of hotels </h3>
								<h5>Plus Get Up to 7% Member Rewards</h5>
								<h6>* conditions apply</h6><h6>
							</h6></div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Carousel -->

			<!-- desktop banner -->
			<div class="visible-desktop" id="dkt_banner">
		
				<!-- Desktop region tabs -->
					<div id="regionTabs">

					<!-- Tabs -->
					<div id="deal-tabs" class="tabbable deal-tabs">
						<div class="dropdown clearfix">
				<ul class="dropdown-menu desktop-tabs" style="display:block">
					<li class="active dropdown-submenu level1" >
					   <a tabindex="-1" href="/en/test-campaign/Austalia-NZ">Australia & NZ</a>
							<ul class="dropdown-menu level2">
								<li>
								<a tabindex="-1" href="/en/test-campaign/Austalia-NZ/Sydney">Sydney</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="/en/test-campaign/Austalia-NZ/Melbourne">Melbourne</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="/en/test-campaign/Austalia-NZ/Brisbane">Brisbane</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="/en/test-campaign/Austalia-NZ/Auckland">Auckland</a>
								</li>
							</ul>
						</li>
						
						<li class="dropdown-submenu level1" >
						<a tabindex="-1" href="/en/test-campaign/USA">USA</a>
							<ul class="dropdown-menu level2">
								<li>
								<a tabindex="-1" href="/en/test-campaign/USA/New-york">New york</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="/en/test-campaign/USA/Washington">Washington</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="/en/test-campaign/USA/California">California</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="/en/test-campaign/USA/Chicago">Chicago</a>
								</li>
							</ul>
						</li>
						
						<li class="dropdown-submenu level1" >
						<a tabindex="-1" href="/en/test-campaign/Europe">Europe</a>
							<ul class="dropdown-menu level2">
								<li>
								<a tabindex="-1" href="/en/test-campaign/Europe/London">London</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="/en/test-campaign/Europe/German">German</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="/en/test-campaign/Europe/Italy">Italy</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="/en/test-campaign/Europe/France">France</a>
								</li>
							</ul>
						</li>
						
						<li class="dropdown-submenu level1" >
						<a tabindex="-1" href="/en/test-campaign/Asia">Asia</a>
							<ul class="dropdown-menu level2">
								<li>
								<a tabindex="-1" href="/en/test-campaign/Asia/india">India</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="/en/test-campaign/Asia/China">China</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="/en/test-campaign/Asia/Singapore">Singapore</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="/en/test-campaign/Asia/Srilanka">Srilanka</a>
								</li>
							</ul>
						</li>
				</ul>
	  </div>
						
					</div>	
					<div class="clearfix"></div>
		<div class="red-line"></div>
				</div>

				<!-- /Desktop region tabs -->
				
			</div>
			<!-- /desktop banner -->
			
			<!-- tablet banner -->
			<div class="visible-tablet" id="tab_banner">
				<!-- sort by options -->

				<div id="sort_by">
					<div class="row">Sort by:
						<span class="col-md-1"><a title="Best Value" href="#">Best Value</a></span>
						<span class="col-md-1"><a title="Lowest Price" href="#">Lowest Price</a></span>
						<span class="col-md-1"><a title="Distance" href="#">Distance</a></span>
						<span class="col-md-1"><a title="Star Rating" href="#">Star Rating</a></span>
						<span class="col-md-1"><a title="Reviewer Score" href="#">Reviewer Score</a></span>
					</div>
				</div>
				<!-- /sort by options -->
				
			</div>
			<!-- /tablet banner -->
			
			<!-- mobile banner -->

			<div class="visible-phone" id="mbl_banner">
			<!-- Button trigger modal -->
	
<!-- Dialog box phone Tabs -->
<!-- Modal -->
<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button aria-hidden="true" data-dismiss="modal" class="close" type="button">?</button>
        <h2 id="myModalLabel" class="modal-title">Find a hotel deal</h2>
      </div>
      <div class="modal-body">
						<form form"="" name="searchBot role=" method="get" class="form-inline datepicker">
							<div class=" where">
								<h5>Where</h5>
								<input type="text" id="locationText" placeholder="Location.." class="form-control input-md">
							</div>	
							<div class="checkdate form-group ">
								<h5>Check-in</h5>
								<input type="text" placeholder="dd/mm/yy" class="check-input form-control input-sm ">
							</div>
							<div class="checkdate">
								<h5>Check-out</h5>
								<input type="text" placeholder="dd/mm/yy" class="check-input form-control input-sm ">
							</div>								
							<div class="controls">
							<div class="errorMessage">&nbsp;</div>	
								<input type="button" name="search" value="Search" onclick="doSearch(this.form)" class="btn btn-search">
							</div>

							<div class=" promo-code">                        
								<p></p><h5>I have a promotion code</h5><p></p>
								<input type="text" placeholder="Location.." class="form-control input-md" id="couponCode" name="couponCode">
							</div>                        
						</form>				
      </div>
   </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="Regions" class="modal fade">
  <div class="modal-dialog">
       <div class="modal-body">
			<div class="dropdown clearfix">
				<ul class="dropdown-menu" style="display:block">
					<li class="dropdown-submenu level1" >
					   <a tabindex="-1" href="#tab1">Australia & NZ</a>
							<ul class="dropdown-menu level2">
								<li>
								<a tabindex="-1" href="#tab1">Sydney</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="#tab2">Melbourne</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="#tab3">Brisbane</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="#tab4">Auckland</a>
								</li>
							</ul>
						</li>
						<li class="divider"></li>
						<li class="dropdown-submenu level1" >
						<a tabindex="-1" href="#tab2">USA</a>
							<ul class="dropdown-menu level2">
								<li>
								<a tabindex="-1" href="#tab1">New york</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="#tab2">Washington</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="#tab3">California</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="#tab4">Chicago</a>
								</li>
							</ul>
						</li>
						<li class="divider"></li>
						<li class="dropdown-submenu level1" >
						<a tabindex="-1" href="#tab3">Europe</a>
							<ul class="dropdown-menu level2">
								<li>
								<a tabindex="-1" href="#tab1">London</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="#tab2">German</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="#tab3">Italy</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="#tab4">France</a>
								</li>
							</ul>
						</li>
						<li class="divider"></li>
						<li class="dropdown-submenu level1" >
						<a tabindex="-1" href="#tab4">Asia</a>
							<ul class="dropdown-menu level2">
								<li>
								<a tabindex="-1" href="#tab1">India</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="#tab2">China</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="#tab3">Singapore</a>
								</li>
								<li class="divider"></li>
								<li>
								<a tabindex="-1" href="#tab4">Srilanka</a>
								</li>
							</ul>
						</li>
				</ul>
	  </div>
	</div>
  
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

				<table width="100%">
					<tbody><tr>
						<td width="50%">
						<div id="accordion" class="panel-group">
									<div class="panel">
										<div class="panel-heading">
										<ul class="nav nav-tabs">
											<li  class="dropdown">
										 <a class="dropdown-toggle" data-target="#Regions" data-toggle="modal" href="#">Australia & NZ<b class="caret"></b></a>
										
										</div>
									</div>
								</div>
						</td>
						<td align="right">
								<div id="accordion" class="panel-group">
									<div class="panel">
										<div class="panel-heading">
										<a data-target="#myModal" data-toggle="modal" href="#">Search more hotels <span class="right-caret"></span> </a>
										</div>
									</div>
								</div>
						</td>
					</tr>
					</tbody></table>	
			</div>
		<!-- Dialog box phone Tabs -->			
			<!-- /mobile banner -->
		</div>
		<!-- END VIEW PARTIAL: banner.phtml -->
        <!-- START VIEW PARTIAL: hotel/item list -->
        <!-- Hotel List -->

        <div class="clearfix"></div>
        <div id="hotelList" class="subContainer">
        <div class="row">
        <!-- Visible Desktop/Tablets Hotel Item List -->
        <div class="tab-content hidden-phone">
        <div class=" tab-pane active" id="tab1">
        <!--Forloop Starts-->
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-xs-4 col-md-5" id="image_section">
                    <a>
                        <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="img-responsive" id="image_hotel" alt="Responsive image"  />
                        <div class="hotel-image-text">
                            <div class="location-text">Bangkok</div>
                            <div class="star4">
                                <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                            </div>
                        </div>

                    </a>
                </div>

                <div class="middle-offer-section col-xs-8 col-md-7">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a>
                                <div class="purple-color" title="Mode Sathorn Hotel">Mode Sathorn Hotel</div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" >
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
                        </div>
                    </div>
                    <div class="saveBookInfo col-xs-4 col-md-2">
                        Save<br> <span class="percentage">50%</span>
                        <div class="clearfix "></div>
                        <div class="btn button">
                            <a>Book</a>
                        </div><br>
                        <p class="inclusions">Travel: Now - 31/12/2013</p>
                    </div>
                </div>


            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-xs-4 col-md-5" id="image_section">
                    <a>
                        <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="img-responsive" id="image_hotel" alt="Responsive image"  />
                        <div class="hotel-image-text">
                            <div class="location-text">Bangkok</div>
                            <div class="star4">
                                <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                            </div>
                        </div>

                    </a>
                </div>

                <div class="middle-offer-section col-xs-8 col-md-7">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a>
                                <div class="purple-color" title="Mode Sathorn Hotel">Mode Sathorn Hotel</div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" >
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
                        </div>
                    </div>
                    <div class="saveBookInfo col-xs-4 col-md-2">
                        Save<br> <span class="percentage">50%</span>
                        <div class="clearfix "></div>
                        <div class="btn button">
                            <a>Book</a>
                        </div><br>
                        <p class="inclusions">Travel: Now - 31/12/2013</p>
                    </div>
                </div>


            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-xs-4 col-md-5" id="image_section">
                    <a>
                        <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="img-responsive" id="image_hotel" alt="Responsive image"  />
                        <div class="hotel-image-text">
                            <div class="location-text">Bangkok</div>
                            <div class="star4">
                                <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                            </div>
                        </div>

                    </a>
                </div>

                <div class="middle-offer-section col-xs-8 col-md-7">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a>
                                <div class="purple-color" title="Mode Sathorn Hotel">Mode Sathorn Hotel</div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" >
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
                        </div>
                    </div>
                    <div class="saveBookInfo col-xs-4 col-md-2">
                        Save<br> <span class="percentage">50%</span>
                        <div class="clearfix "></div>
                        <div class="btn button">
                            <a>Book</a>
                        </div><br>
                        <p class="inclusions">Travel: Now - 31/12/2013</p>
                    </div>
                </div>


            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-xs-4 col-md-5" id="image_section">
                    <a>
                        <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="img-responsive" id="image_hotel" alt="Responsive image"  />
                        <div class="hotel-image-text">
                            <div class="location-text">Bangkok</div>
                            <div class="star4">
                                <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                            </div>
                        </div>

                    </a>
                </div>

                <div class="middle-offer-section col-xs-8 col-md-7">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a>
                                <div class="purple-color" title="Mode Sathorn Hotel">Mode Sathorn Hotel</div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" >
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
                        </div>
                    </div>
                    <div class="saveBookInfo col-xs-4 col-md-2">
                        Save<br> <span class="percentage">50%</span>
                        <div class="clearfix "></div>
                        <div class="btn button">
                            <a>Book</a>
                        </div><br>
                        <p class="inclusions">Travel: Now - 31/12/2013</p>
                    </div>
                </div>


            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-xs-4 col-md-5" id="image_section">
                    <a>
                        <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="img-responsive" id="image_hotel" alt="Responsive image"  />
                        <div class="hotel-image-text">
                            <div class="location-text">Bangkok</div>
                            <div class="star4">
                                <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                            </div>
                        </div>

                    </a>
                </div>

                <div class="middle-offer-section col-xs-8 col-md-7">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a>
                                <div class="purple-color" title="Mode Sathorn Hotel">Mode Sathorn Hotel</div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" >
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
                        </div>
                    </div>
                    <div class="saveBookInfo col-xs-4 col-md-2">
                        Save<br> <span class="percentage">50%</span>
                        <div class="clearfix "></div>
                        <div class="btn button">
                            <a>Book</a>
                        </div><br>
                        <p class="inclusions">Travel: Now - 31/12/2013</p>
                    </div>
                </div>


            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-xs-4 col-md-5" id="image_section">
                    <a>
                        <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="img-responsive" id="image_hotel" alt="Responsive image"  />
                        <div class="hotel-image-text">
                            <div class="location-text">Bangkok</div>
                            <div class="star4">
                                <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                            </div>
                        </div>

                    </a>
                </div>

                <div class="middle-offer-section col-xs-8 col-md-7">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a>
                                <div class="purple-color" title="Mode Sathorn Hotel">Mode Sathorn Hotel</div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" >
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
                        </div>
                    </div>
                    <div class="saveBookInfo col-xs-4 col-md-2">
                        Save<br> <span class="percentage">50%</span>
                        <div class="clearfix "></div>
                        <div class="btn button">
                            <a>Book</a>
                        </div><br>
                        <p class="inclusions">Travel: Now - 31/12/2013</p>
                    </div>
                </div>


            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-xs-4 col-md-5" id="image_section">
                    <a>
                        <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="img-responsive" id="image_hotel" alt="Responsive image"  />
                        <div class="hotel-image-text">
                            <div class="location-text">Bangkok</div>
                            <div class="star4">
                                <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                            </div>
                        </div>

                    </a>
                </div>

                <div class="middle-offer-section col-xs-8 col-md-7">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a>
                                <div class="purple-color" title="Mode Sathorn Hotel">Mode Sathorn Hotel</div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" >
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
                        </div>
                    </div>
                    <div class="saveBookInfo col-xs-4 col-md-2">
                        Save<br> <span class="percentage">50%</span>
                        <div class="clearfix "></div>
                        <div class="btn button">
                            <a>Book</a>
                        </div><br>
                        <p class="inclusions">Travel: Now - 31/12/2013</p>
                    </div>
                </div>


            </div>
            <div class="clearfix "></div>
        </div>
        <!--Forloop Ends-->
        </div>

        <div class=" tab-pane" id="tab2">
        <!--Forloop Starts-->
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-md-5" id="image_section">
                    <a>
                        <div>
                            <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_307928.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>
                            <!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
                            <div class="hotel-image-text">
                                <div class="location-text">Austalia</div>
                                <div class="star4">
                                    <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="middle-offer-section col-md-5">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a>
                                <div class="purple-color" title="Mode Sathorn Hotel">Landmark Hotel </div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
														<span>
															<!-- Show_JoinHotelClub_Popup()-->
															<p>Freebies Included</p>
															<p>Find out more &gt;&gt;</p>
														</span>
                        </div>
                    </div>
                </div>

                <div class="saveBookInfo col-md-2">
                    Save<br> <span class="percentage">50%</span>
                    <div class="clearfix "></div>
                    <div class="btn button">
                        <a>Book</a>
                    </div><br>
                    <p class="inclusions">Travel: Now - 31/12/2013</p>
                </div>
            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-md-5" id="image_section">
                    <a>
                        <div>
                            <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_307928.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>
                            <!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
                            <div class="hotel-image-text">
                                <div class="location-text">Austalia</div>
                                <div class="star4">
                                    <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="middle-offer-section col-md-5">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a>
                                <div class="purple-color" title="Mode Sathorn Hotel">Landmark Hotel </div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
														<span>
															<!-- Show_JoinHotelClub_Popup()-->
															<p>Freebies Included</p>
															<p>Find out more &gt;&gt;</p>
														</span>
                        </div>
                    </div>
                </div>

                <div class="saveBookInfo col-md-2">
                    Save<br> <span class="percentage">50%</span>
                    <div class="clearfix "></div>
                    <div class="btn button">
                        <a>Book</a>
                    </div><br>
                    <p class="inclusions">Travel: Now - 31/12/2013</p>
                </div>
            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-md-5" id="image_section">
                    <a>
                        <div>
                            <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_307928.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>
                            <!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
                            <div class="hotel-image-text">
                                <div class="location-text">Austalia</div>
                                <div class="star4">
                                    <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="middle-offer-section col-md-5">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a>
                                <div class="purple-color" title="Mode Sathorn Hotel">Landmark Hotel </div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
														<span>
															<!-- Show_JoinHotelClub_Popup()-->
															<p>Freebies Included</p>
															<p>Find out more &gt;&gt;</p>
														</span>
                        </div>
                    </div>
                </div>

                <div class="saveBookInfo col-md-2">
                    Save<br> <span class="percentage">50%</span>
                    <div class="clearfix "></div>
                    <div class="btn button">
                        <a>Book</a>
                    </div><br>
                    <p class="inclusions">Travel: Now - 31/12/2013</p>
                </div>
            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-md-5" id="image_section">
                    <a>
                        <div>
                            <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_307928.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>
                            <!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
                            <div class="hotel-image-text">
                                <div class="location-text">Austalia</div>
                                <div class="star4">
                                    <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="middle-offer-section col-md-5">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a>
                                <div class="purple-color" title="Mode Sathorn Hotel">Landmark Hotel </div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
														<span>
															<!-- Show_JoinHotelClub_Popup()-->
															<p>Freebies Included</p>
															<p>Find out more &gt;&gt;</p>
														</span>
                        </div>
                    </div>
                </div>

                <div class="saveBookInfo col-md-2">
                    Save<br> <span class="percentage">50%</span>
                    <div class="clearfix "></div>
                    <div class="btn button">
                        <a>Book</a>
                    </div><br>
                    <p class="inclusions">Travel: Now - 31/12/2013</p>
                </div>
            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-md-5" id="image_section">
                    <a>
                        <div>
                            <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_307928.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>
                            <!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
                            <div class="hotel-image-text">
                                <div class="location-text">Austalia</div>
                                <div class="star4">
                                    <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="middle-offer-section col-md-5">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a>
                                <div class="purple-color" title="Mode Sathorn Hotel">Landmark Hotel </div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
														<span>
															<!-- Show_JoinHotelClub_Popup()-->
															<p>Freebies Included</p>
															<p>Find out more &gt;&gt;</p>
														</span>
                        </div>
                    </div>
                </div>

                <div class="saveBookInfo col-md-2">
                    Save<br> <span class="percentage">50%</span>
                    <div class="clearfix "></div>
                    <div class="btn button">
                        <a>Book</a>
                    </div><br>
                    <p class="inclusions">Travel: Now - 31/12/2013</p>
                </div>
            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-md-5" id="image_section">
                    <a>
                        <div>
                            <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_307928.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>
                            <!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
                            <div class="hotel-image-text">
                                <div class="location-text">Austalia</div>
                                <div class="star4">
                                    <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="middle-offer-section col-md-5">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a>
                                <div class="purple-color" title="Mode Sathorn Hotel">Landmark Hotel </div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
														<span>
															<!-- Show_JoinHotelClub_Popup()-->
															<p>Freebies Included</p>
															<p>Find out more &gt;&gt;</p>
														</span>
                        </div>
                    </div>
                </div>

                <div class="saveBookInfo col-md-2">
                    Save<br> <span class="percentage">50%</span>
                    <div class="clearfix "></div>
                    <div class="btn button">
                        <a>Book</a>
                    </div><br>
                    <p class="inclusions">Travel: Now - 31/12/2013</p>
                </div>
            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-md-5" id="image_section">
                    <a>
                        <div>
                            <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_307928.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>
                            <!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
                            <div class="hotel-image-text">
                                <div class="location-text">Austalia</div>
                                <div class="star4">
                                    <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="middle-offer-section col-md-5">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a>
                                <div class="purple-color" title="Mode Sathorn Hotel">Landmark Hotel </div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
														<span>
															<!-- Show_JoinHotelClub_Popup()-->
															<p>Freebies Included</p>
															<p>Find out more &gt;&gt;</p>
														</span>
                        </div>
                    </div>
                </div>

                <div class="saveBookInfo col-md-2">
                    Save<br> <span class="percentage">50%</span>
                    <div class="clearfix "></div>
                    <div class="btn button">
                        <a>Book</a>
                    </div><br>
                    <p class="inclusions">Travel: Now - 31/12/2013</p>
                </div>
            </div>
            <div class="clearfix "></div>
        </div>
        <!--Forloop Ends-->
        </div>

        <div class=" tab-pane" id="tab3">
        <!--Forloop Starts-->
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-md-5" id="image_section">
                    <a>
                        <div>
                            <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_316563.jpg" class="img-responsive"  alt="Responsive image" id="image_hotel" width="180" height="120"/>
                            <div class="hotel-image-text">
                                <div class="location-text">UK</div>
                                <div class="star4">
                                    <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="middle-offer-section col-md-5">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a>
                                <div class="purple-color" title="Mode Sathorn Hotel">Jupiters Hotel and ...</div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
                        </div>
                    </div>
                </div>

                <div class="saveBookInfo col-md-2">
                    Save<br> <span class="percentage">50%</span>
                    <div class="clearfix "></div>
                    <div class="btn button">
                        <a >Book</a>
                    </div><br>
                    <p class="inclusions">Travel: Now - 31/12/2013</p>
                </div>
            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-md-5" id="image_section">
                    <a>
                        <div>
                            <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_316563.jpg" class="img-responsive"  alt="Responsive image" id="image_hotel" width="180" height="120"/>
                            <div class="hotel-image-text">
                                <div class="location-text">UK</div>
                                <div class="star4">
                                    <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="middle-offer-section col-md-5">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a>
                                <div class="purple-color" title="Mode Sathorn Hotel">Jupiters Hotel and ...</div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
                        </div>
                    </div>
                </div>

                <div class="saveBookInfo col-md-2">
                    Save<br> <span class="percentage">50%</span>
                    <div class="clearfix "></div>
                    <div class="btn button">
                        <a >Book</a>
                    </div><br>
                    <p class="inclusions">Travel: Now - 31/12/2013</p>
                </div>
            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-md-5" id="image_section">
                    <a>
                        <div>
                            <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_316563.jpg" class="img-responsive"  alt="Responsive image" id="image_hotel" width="180" height="120"/>
                            <div class="hotel-image-text">
                                <div class="location-text">UK</div>
                                <div class="star4">
                                    <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="middle-offer-section col-md-5">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a>
                                <div class="purple-color" title="Mode Sathorn Hotel">Jupiters Hotel and ...</div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
                        </div>
                    </div>
                </div>

                <div class="saveBookInfo col-md-2">
                    Save<br> <span class="percentage">50%</span>
                    <div class="clearfix "></div>
                    <div class="btn button">
                        <a >Book</a>
                    </div><br>
                    <p class="inclusions">Travel: Now - 31/12/2013</p>
                </div>
            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-md-5" id="image_section">
                    <a>
                        <div>
                            <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_316563.jpg" class="img-responsive"  alt="Responsive image" id="image_hotel" width="180" height="120"/>
                            <div class="hotel-image-text">
                                <div class="location-text">UK</div>
                                <div class="star4">
                                    <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="middle-offer-section col-md-5">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a>
                                <div class="purple-color" title="Mode Sathorn Hotel">Jupiters Hotel and ...</div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
                        </div>
                    </div>
                </div>

                <div class="saveBookInfo col-md-2">
                    Save<br> <span class="percentage">50%</span>
                    <div class="clearfix "></div>
                    <div class="btn button">
                        <a >Book</a>
                    </div><br>
                    <p class="inclusions">Travel: Now - 31/12/2013</p>
                </div>
            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-md-5" id="image_section">
                    <a>
                        <div>
                            <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_316563.jpg" class="img-responsive"  alt="Responsive image" id="image_hotel" width="180" height="120"/>
                            <div class="hotel-image-text">
                                <div class="location-text">UK</div>
                                <div class="star4">
                                    <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="middle-offer-section col-md-5">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a>
                                <div class="purple-color" title="Mode Sathorn Hotel">Jupiters Hotel and ...</div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
                        </div>
                    </div>
                </div>

                <div class="saveBookInfo col-md-2">
                    Save<br> <span class="percentage">50%</span>
                    <div class="clearfix "></div>
                    <div class="btn button">
                        <a >Book</a>
                    </div><br>
                    <p class="inclusions">Travel: Now - 31/12/2013</p>
                </div>
            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-md-5" id="image_section">
                    <a>
                        <div>
                            <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_316563.jpg" class="img-responsive"  alt="Responsive image" id="image_hotel" width="180" height="120"/>
                            <div class="hotel-image-text">
                                <div class="location-text">UK</div>
                                <div class="star4">
                                    <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="middle-offer-section col-md-5">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a>
                                <div class="purple-color" title="Mode Sathorn Hotel">Jupiters Hotel and ...</div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
                        </div>
                    </div>
                </div>

                <div class="saveBookInfo col-md-2">
                    Save<br> <span class="percentage">50%</span>
                    <div class="clearfix "></div>
                    <div class="btn button">
                        <a >Book</a>
                    </div><br>
                    <p class="inclusions">Travel: Now - 31/12/2013</p>
                </div>
            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-md-5" id="image_section">
                    <a>
                        <div>
                            <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_316563.jpg" class="img-responsive"  alt="Responsive image" id="image_hotel" width="180" height="120"/>
                            <div class="hotel-image-text">
                                <div class="location-text">UK</div>
                                <div class="star4">
                                    <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="middle-offer-section col-md-5">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a>
                                <div class="purple-color" title="Mode Sathorn Hotel">Jupiters Hotel and ...</div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
                        </div>
                    </div>
                </div>

                <div class="saveBookInfo col-md-2">
                    Save<br> <span class="percentage">50%</span>
                    <div class="clearfix "></div>
                    <div class="btn button">
                        <a >Book</a>
                    </div><br>
                    <p class="inclusions">Travel: Now - 31/12/2013</p>
                </div>
            </div>
            <div class="clearfix "></div>
        </div>
        <!--Forloop Ends-->
        </div>
        <div class="tab-pane" id="tab4">
        <!--Forloop Starts-->
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-md-5" id="image_section">
                    <a>
                        <div>
                            <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_23106.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>
                            <!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
                            <div class="hotel-image-text">
                                <div class="location-text">Bangkok</div>
                                <div class="star4">
                                    <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="middle-offer-section col-md-5">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a href="javascript:void(0);">
                                <div class="purple-color" title="Mode Sathorn Hotel">Villa Alessandra</div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
                        </div>
                    </div>
                </div>

                <div class="saveBookInfo col-md-2">
                    Save<br> <span class="percentage">50%</span>
                    <div class="clearfix "></div>
                    <div class="btn button">
                        <a>Book</a>
                    </div><br>
                    <p class="inclusions">Travel: Now - 31/12/2013</p>
                </div>
            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-md-5" id="image_section">
                    <a>
                        <div>
                            <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_23106.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>
                            <!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
                            <div class="hotel-image-text">
                                <div class="location-text">Bangkok</div>
                                <div class="star4">
                                    <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="middle-offer-section col-md-5">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a href="javascript:void(0);">
                                <div class="purple-color" title="Mode Sathorn Hotel">Villa Alessandra</div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
                        </div>
                    </div>
                </div>

                <div class="saveBookInfo col-md-2">
                    Save<br> <span class="percentage">50%</span>
                    <div class="clearfix "></div>
                    <div class="btn button">
                        <a>Book</a>
                    </div><br>
                    <p class="inclusions">Travel: Now - 31/12/2013</p>
                </div>
            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-md-5" id="image_section">
                    <a>
                        <div>
                            <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_23106.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>
                            <!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
                            <div class="hotel-image-text">
                                <div class="location-text">Bangkok</div>
                                <div class="star4">
                                    <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="middle-offer-section col-md-5">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a href="javascript:void(0);">
                                <div class="purple-color" title="Mode Sathorn Hotel">Villa Alessandra</div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
                        </div>
                    </div>
                </div>

                <div class="saveBookInfo col-md-2">
                    Save<br> <span class="percentage">50%</span>
                    <div class="clearfix "></div>
                    <div class="btn button">
                        <a>Book</a>
                    </div><br>
                    <p class="inclusions">Travel: Now - 31/12/2013</p>
                </div>
            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-md-5" id="image_section">
                    <a>
                        <div>
                            <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_23106.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>
                            <!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
                            <div class="hotel-image-text">
                                <div class="location-text">Bangkok</div>
                                <div class="star4">
                                    <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="middle-offer-section col-md-5">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a href="javascript:void(0);">
                                <div class="purple-color" title="Mode Sathorn Hotel">Villa Alessandra</div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
                        </div>
                    </div>
                </div>

                <div class="saveBookInfo col-md-2">
                    Save<br> <span class="percentage">50%</span>
                    <div class="clearfix "></div>
                    <div class="btn button">
                        <a>Book</a>
                    </div><br>
                    <p class="inclusions">Travel: Now - 31/12/2013</p>
                </div>
            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-md-5" id="image_section">
                    <a>
                        <div>
                            <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_23106.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>
                            <!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
                            <div class="hotel-image-text">
                                <div class="location-text">Bangkok</div>
                                <div class="star4">
                                    <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="middle-offer-section col-md-5">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a href="javascript:void(0);">
                                <div class="purple-color" title="Mode Sathorn Hotel">Villa Alessandra</div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
                        </div>
                    </div>
                </div>

                <div class="saveBookInfo col-md-2">
                    Save<br> <span class="percentage">50%</span>
                    <div class="clearfix "></div>
                    <div class="btn button">
                        <a>Book</a>
                    </div><br>
                    <p class="inclusions">Travel: Now - 31/12/2013</p>
                </div>
            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-md-5" id="image_section">
                    <a>
                        <div>
                            <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_23106.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>
                            <!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
                            <div class="hotel-image-text">
                                <div class="location-text">Bangkok</div>
                                <div class="star4">
                                    <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="middle-offer-section col-md-5">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a href="javascript:void(0);">
                                <div class="purple-color" title="Mode Sathorn Hotel">Villa Alessandra</div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
                        </div>
                    </div>
                </div>

                <div class="saveBookInfo col-md-2">
                    Save<br> <span class="percentage">50%</span>
                    <div class="clearfix "></div>
                    <div class="btn button">
                        <a>Book</a>
                    </div><br>
                    <p class="inclusions">Travel: Now - 31/12/2013</p>
                </div>
            </div>
            <div class="clearfix "></div>
        </div>
        <div class="hotelDeal col-xs-12 col-md-6" style="cursor: default;">
            <div class="row">
                <div class="image_section col-md-5" id="image_section">
                    <a>
                        <div>
                            <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_23106.jpg" class="img-responsive" id="image_hotel" alt="Responsive image" width="180" height="120"/>
                            <!--<img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class="hotelimg" />-->
                            <div class="hotel-image-text">
                                <div class="location-text">Bangkok</div>
                                <div class="star4">
                                    <img src="http://www.hotelclub.com/ad-unit/images/ce-hotelstar-brand.png" class="img-responsive ce-star" id="image_hotel" alt="Responsive image" width="148" height="12" />
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="middle-offer-section col-md-5">
                    <div class="hotelInfo">
                        <h3>
                            <!-- HOTEL NAME -->
                            <a href="javascript:void(0);">
                                <div class="purple-color" title="Mode Sathorn Hotel">Villa Alessandra</div>
                            </a>
                        </h3>
                        <div class="campaign-promo-offer">Save 50%</div>
                        <input type="hidden" value="Save 50%" id="hotel_inc1_1149971">
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png">
                            <div class="font_red member-extras-text">Member Extras</div>
                        </div>
                        <div class="sign-in-member-offer offer-for-existing-members font_red">Save 55%</div>
                        <div class="sign-out-member-offer" style="display: none;">
												<span>
													<!-- Show_JoinHotelClub_Popup()-->
													<p>Freebies Included</p>
													<p>Find out more &gt;&gt;</p>
												</span>
                        </div>
                    </div>
                </div>

                <div class="saveBookInfo col-md-2">
                    Save<br> <span class="percentage">50%</span>
                    <div class="clearfix "></div>
                    <div class="btn button">
                        <a>Book</a>
                    </div><br>
                    <p class="inclusions">Travel: Now - 31/12/2013</p>
                </div>
            </div>
            <div class="clearfix "></div>
        </div>
        <!--Forloop Ends-->
        </div>
        </div>
        <!-- /Visible Desktop/Tablets Hotel Item List -->
        </div>
        <!-- Visible Phone Hotel Item List -->

        <div class="visible-phone" >

            <!--Forloop Starts-->
            <?php for($i=0;$i<=6;$i++){ ?>
                <div id="Phone-Itemcard" class="hotelCard" style="cursor: default;">
                    <!-- image -->
                    <div class="hote_image" id="image_section">
                        <a>
                            <img src="http://www.hotelclub.com/ad-unit/promodeals/images/mp_v1_1149971.jpg" class=" img-responsive"  alt="Hotel Image"  />
                        </a>
                    </div>
                    <!-- details -->
                    <div class=" middle-offer-section ">
                        <div class="purple-color" title="Mode Sathorn Hotel"><a>Mode Sathorn Hotel</a></div>
                        <div class="rating ">
                            <img src="img/stars-3.png" class="img-responsive rating-star" id="image_hotel" alt="rating image"  />
                        </div>
                        <div class="hotel-image-text">
                            <div class="location-text">Bangkok</div>
                        </div>
                        <div class="members-extras-block">
                            <!-- The Big Red Plus Sign -->
                            <img class="members-extras-logo img-responsive" alt="Member Rewards" src="//www.hotelclub.com/Ad-unit/images/member-rewards_20x20.png" >
                            <div class="font_red">Member Extras</div>
                            <div class="sign-out-member-offer">
                                <p>Freebies Included</p>
                                <p>Find out more &gt;&gt;</p>

                            </div>
                        </div>
                    </div>
                    <!-- offer -->

                    <div class="deals">
                        <div class="offers_rate" style="color:red; padding:3px;">
                            <span>save</span><p style="">&nbsp;</p><span class="offers_percentage">80<sup>%</sup></span>
                        </div>
                        <div class="button_book"><a>Book</a></div>
                        <div class="valid_dates" >
                            <p>Travel dates </p>
                            <p>27 june - 27 july </p>
                        </div>
                    </div>


                    <div class="clearfix"></div>
                </div>
            <?php } ?>
            <!--Forloop Ends-->

            <!-- /Visible Phone Hotel Item List -->

        </div> <!-- /Hotel List -->

        <!-- END VIEW PARTIAL: hotel/item list -->
	</div>
	
	<!-- include external js -->
	<script src="http://code.jquery.com/jquery.js"></script>
	<script src="bootstrap/js/bootstrap.min.js"></script>
	<!-- /include external js -->
</body>
</html> 