<!DOCTYPE HTML>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Hotel Club - Great Holidays - Header</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- include bootstrap -->
	<link href="bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
	<link href="bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
	<link href="css/hc_great_holidays.css" rel="stylesheet" media="screen">
</head>
<body>
	<div class="container">
		
		<!-- START VIEW PARTIAL: header.phtml -->
		<div id="header" class="subContainer">
			
			<!-- desktop header -->
			<div id="dkt_header" class="visible-desktop">
				<div class="row">
					
					<!-- header logo -->
					<div class="col-md-5 logo">
						<a href="index.html" title="Hotelclub Logo">
							<img src="http://www.tnetnoc.com/static/28.64.9/image/pos/hcl/en-au/logo-header.png" alt="Hotelclub Logo" />
						</a>
					</div>
					
					<!-- header links -->
					<div class="col-md-offset-5">
						<ul class="primary">
							<li><a rel="nofollow" class="link" href="https://www.hotelclub.com/trips/current">My Bookings</a></li>
							<li><a rel="nofollow" class="link" href="https://www.hotelclub.com/account/myclub">My Club</a></li>
							<li><a rel="nofollow" class="link" href="https://www.hotelclub.com/account/myprofile">My Account</a></li>
							<li><a rel="nofollow" class="link" href="https://www.hotelclub.com/trips/writeReview">Write a review</a> </li>
							<li class="last"><a rel="nofollow" class="link" href="http://faq.hotelclub.com">Customer Service</a></li>
						</ul>				
								
						<ul class="login">
							<li class="welcomeText">Welcome sanand </li>
							<li class="loyaltyTier">Silver Member:</li>
							<li class="loyaltyInfo">0.00 Member Rewards** (Rs.0.00)</li>
							<li class="signOutLink"><a rel="nofollow" class="link" href="https://www.hotelclub.com/account/logout">Sign out</a></li>
						</ul>
					</div>
				
				</div>
			</div>
			<!-- /desktop header -->
			
			<!-- mobile header -->
			<div id="mbl_header" class="hidden-desktop">
				<div id="mbl_menu">
					<div class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">
							<img src="img/mobile_menu.png" alt="Main Menu" />
						</a>
						<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
							<li><a href="#" alt="Hotel">Hotel</a></li>
							<li><a href="#" alt="Club Benefits">Club Benefits</a></li>
							<li><a href="#" alt="English">English</a></li>
							<li><a href="#" alt="AUD - Australian Dollar">AUD - Australian Dollar</a></li>
							<li><a href="#" alt="Customer Service">Customer Service</a></li>
						</ul>
					</div>
				</div>
				
				<div id="mbl_logo">
					<a href="index.html" title="Hotelclub Logo">
						<img src="http://www.tnetnoc.com/static/28.65.6/image/pos/hcl/en-au/logo-tablet.png" alt="Hotelclub Logo" />
					</a>
				</div>
				
				<div id="mbl_member">
					<div class="dropdown pull-right">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">
							<img src="img/mobile_member.png" alt="Member Menu" /> <span class="visible-tablet">Welcome</span>
						</a>
						<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel2">
							<li><a href="#" alt="My Bookings">My Bookings</a></li> 
							<li><a href="#" alt="My Account">My Account</a></li>
							<li><a href="#" alt="Sign in">Sign in</a></li>
							<li><a href="#" alt="Register">Register</a></li>
						</ul>
					</div>
				</div>
				
				<div id="tab_briefcase" class="visible-tablet">
					<img src="img/tab_briefcase.png" alt="Briefcase" />
				</div>
				<div class="clear">&nbsp;</div>
			</div>
			<!-- /mobile header -->
		</div>
		
		<!-- headMenu -->
		<div id="headMenu" class="subContainer visible-desktop">
			<div class="row">
				<!-- main menu -->
				<div class="col-md-6">
					<ul class="left_menu">
						<li>Home</li>
						<li>Life Style Club</li>
					</ul>
				</div>
				
				<!-- lang -->
				<div class="col-md-offset-6">
					<ul class="nav navbar-nav navbar-right right_menu">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">English <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="#">Menu 1</a></li>
								<li><a href="#">Menu 2</a></li>
								<li><a href="#">Menu 3</a></li>
								<li><a href="#">Menu 4</a></li>
							</ul>
						</li>
					</ul>
				</div>
			
			</div>
		</div>
		<!-- /headMenu -->
		
		<!-- END VIEW PARTIAL: header.phtml -->
	</div>
	
	<!-- include external js -->
	<script src="http://code.jquery.com/jquery.js"></script>
	<script src="bootstrap/js/bootstrap.min.js"></script>
	<!-- /include external js -->
</body>
</html>