<html lang="en"><head>
	<meta charset="utf-8">
	<title>Hotel Club - Great Holidays - Banner</title>
	<meta content="width=device-width, initial-scale=1.0" name="viewport">
	<!-- include bootstrap -->
	<link rel="stylesheet" href="bootstrap/css/bootstrap-responsive.css">
	<link media="screen" rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
	<link media="screen" rel="stylesheet" href="css/hc_great_holidays.css">
</head>
<body>
	<div class="container">
		
		<!-- START VIEW PARTIAL: banner.phtml -->
		<div class="subContainer" id="banner">
				<!-- Desktop Search Widget -->
				<div class="clearfix"></div>
					<div class="visible-desktop" id="dkt_searchBot">
						<!-- search -->
						<form form"="" name="searchBot role=" method="get" class="form-inline datepicker">
							<div class=" where">
								<h2>Find a hotel deal</h2>
								<p>Where</p>
								<input type="text" id="locationText" placeholder="Location.." class="form-control input-md">
							</div>	
							<div class="form-group ">
								<p>Check-in</p>
								<input type="text" placeholder="dd/mm/yy" class="form-control input-sm">
							</div>
							<div class="form-group ">
								<p>Check-out</p>
								<input type="text" placeholder="dd/mm/yy" class="form-control input-sm ">
							</div>								
							<div class="controls">
							<div class="errorMessage">&nbsp;</div>	
								<input type="button" name="search" value="Search" onclick="doSearch(this.form)" class="btn btn-default col-md-offset-8">
							</div>
							<div class=" promo-code">                        
								<p>I have a promotion code</p>
								<input type="text" placeholder="Location.." class="form-control input-md" id="couponCode" name="couponCode">
							</div> 
							<div class="search_contacts row">
							<div class="glyphicon glyphicon-earphone col-md-1">
							</div>
							<div class=" help col-md-8">
							<p>Need Help to book ?</p>
							<p>1300 854 585 </p>
							</div>
							</div>
						</form>					
					</div>
				
				<!-- /Desktop Search Widget -->
				<!-- Tablet search widget -->
				<div class="visible-tablet" id="tbt_searchBot">
						<!-- search -->
						<form form"="" name="searchBot role=" method="get" class="form-inline datepicker">
							<div class=" where">
								<h2>Find a hotel deal</h2>
								<p>Where</p>
								<input type="text" id="locationText" placeholder="Location.." class="form-control input-md">
							</div>	
							<div class="form-group ">
								<p>Check-in</p>
								<input type="text" placeholder="dd/mm/yy" class="form-control input-sm">
							</div>
							<div class="form-group ">
								<p>Check-out</p>
								<input type="text" placeholder="dd/mm/yy" class="form-control input-sm ">
							</div>								
							<div class="controls">
							<div class="errorMessage">&nbsp;</div>	
								<input type="button" name="search" value="Search" onclick="doSearch(this.form)" class="btn btn-default col-md-offset-8">
							</div>
							<div class=" promo-code">                        
								<p>I have a promotion code</p>
								<input type="text" placeholder="Location.." class="form-control input-md" id="couponCode" name="couponCode">
							</div> 
							
						</form>					
					</div>
			<!-- /Tablet search widget -->
			<!-- carousel -->
			<div data-interval="2500" data-ride="carousel" class="carousel slide" id="dkt_carousel">
				<ol class="carousel-indicators">
					<li class="" data-slide-to="0" data-target="#dkt_carousel"></li>
					<li data-slide-to="1" data-target="#dkt_carousel" class=""></li>
					<li data-slide-to="2" data-target="#dkt_carousel" class="active"></li>
				</ol>
				<!-- Carousel items -->
				<div class="carousel-inner">
					<div class="item">
						<img alt="Member" src="img/carousel_item1.png">
						<div class="row">
							<div class="carousel-caption visible-tablet col-md-offset-3">
								<h2>Great Holiday Sale ----</h2>
								<h3>Save Upto 50% of hotels </h3>
								<h5>Plus Get Up to 7% Member Rewards</h5>
								<h6>* conditions apply</h6><h6>
							</h6></div>
						</div>
					</div>
					<div class="item">
						<img alt="Member" src="img/carousel_item2.png">
						<div class="row">
							<div class="carousel-caption visible-tablet col-xs-6">
								<h2>Great Holiday Sale ----</h2>
								<h3>Save Upto 50% of hotels </h3>
								<h5>Plus Get Up to 7% Member Rewards</h5>
								<h6>* conditions apply</h6><h6>
							</h6></div>
						</div>
					</div>
					<div class="item active">
						<img alt="Member" src="img/carousel_item3.png">
						<div class="row">
							<div class="carousel-caption visible-tablet col-xs-6">
								<h2>Great Holiday Sale ----</h2>
								<h3>Save Upto 50% of hotels </h3>
								<h5>Plus Get Up to 7% Member Rewards</h5>
								<h6>* conditions apply</h6><h6>
							</h6></div>
						</div>
					</div>
					<div class="item">
						<img alt="Member" src="img/carousel_item4.png">
						<div class="row">
							<div class="carousel-caption visible-tablet col-xs-6">
								<h2>Great Holiday Sale ----</h2>
								<h3>Save Upto 50% of hotels </h3>
								<h5>Plus Get Up to 7% Member Rewards</h5>
								<h6>* conditions apply</h6><h6>
							</h6></div>
						</div>
					</div>
					<div class="item">
						<img alt="Member" src="img/carousel_item5.png">
						<div class="row">
							<div class="carousel-caption visible-tablet col-xs-6">
								<h2>Great Holiday Sale ----</h2>
								<h3>Save Upto 50% of hotels </h3>
								<h5>Plus Get Up to 7% Member Rewards</h5>
								<h6>* conditions apply</h6><h6>
							</h6></div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Carousel -->

			<!-- desktop banner -->
			<div class="visible-desktop" id="dkt_banner">
		
				<!-- region tabs -->
					<div id="regionTabs">
					<!-- Tabs -->
					<div id="deal-tabs" class="tabbable deal-tabs">
						<ul class="nav nav-tabs">
							<li class="active"><a data-toggle="tab" href="#tab1">South East Asia</a></li>
							<li><a data-toggle="tab" href="#tab2">North Asia</a></li>
							<li><a data-toggle="tab" href="#tab3">Australia</a></li>
							<li><a data-toggle="tab" href="#tab4">Europe &amp; US</a></li>
						</ul> 
						
					</div>	
					<div class="clearfix"></div>
		<div class="red-line"></div>
				</div>

				<!-- /region tabs -->
				
			</div>
			<!-- /desktop banner -->
			
			<!-- tablet banner -->
			<div class="visible-tablet" id="tab_banner">
				<!-- sort by options -->

				<div id="sort_by">
					<div class="row">Sort by:
						<span class="col-md-1"><a title="Best Value" href="#">Best Value</a></span>
						<span class="col-md-1"><a title="Lowest Price" href="#">Lowest Price</a></span>
						<span class="col-md-1"><a title="Distance" href="#">Distance</a></span>
						<span class="col-md-1"><a title="Star Rating" href="#">Star Rating</a></span>
						<span class="col-md-1"><a title="Reviewer Score" href="#">Reviewer Score</a></span>
					</div>
				</div>
				<!-- /sort by options -->
				
			</div>
			<!-- /tablet banner -->
			
			<!-- mobile banner -->

			<div class="visible-phone" id="mbl_banner">
			<!-- Button trigger modal -->
	

<!-- Modal -->
<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
        <h2 id="myModalLabel" class="modal-title">Find a hotel deal</h2>
      </div>
      <div class="modal-body">
						<form form"="" name="searchBot role=" method="get" class="form-inline datepicker">
							<div class=" where">
								<h5>Where</h5>
								<input type="text" id="locationText" placeholder="Location.." class="form-control input-md">
							</div>	
							<div class="checkdate form-group ">
								<h5>Check-in</h5>
								<input type="text" placeholder="dd/mm/yy" class="check-input form-control input-sm ">
							</div>
							<div class="checkdate">
								<h5>Check-out</h5>
								<input type="text" placeholder="dd/mm/yy" class="check-input form-control input-sm ">
							</div>								
							<div class="controls">
							<div class="errorMessage">&nbsp;</div>	
								<input type="button" name="search" value="Search" onclick="doSearch(this.form)" class="btn btn-search">
							</div>

							<div class=" promo-code">                        
								<p></p><h5>I have a promotion code</h5><p></p>
								<input type="text" placeholder="Location.." class="form-control input-md" id="couponCode" name="couponCode">
							</div>                        
						</form>				
      </div>
   </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

				<table width="100%">
					<tbody><tr>
						<td width="50%">
							<ul class="nav">
								<li class="dropdown">
									<a href="#" data-toggle="dropdown" class="dropdown-toggle">Australia &amp; NZ 
									<span class="caret "></span> </a>
									<ul aria-labelledby="dLabel" role="menu" class="dropdown-menu">
										<li><a data-toggle="tab" href="#tab1">South East Asia</a></li>
										<li><a data-toggle="tab" href="#tab2">North Asia</a></li>
										<li><a data-toggle="tab" href="#tab3">Australia &amp; NZ</a></li>
										<li><a data-toggle="tab" href="#tab4">Europe &amp; US</a></li>
									</ul>
								</li>
							</ul>
						</td>
						<td align="right">
								<div id="accordion" class="panel-group">
									<div class="panel">
										<div class="panel-heading">
										<a data-target="#myModal" data-toggle="modal" href="#">Search more hotels <span class="right-caret"></span> </a>
										</div>
									</div>
								</div>
						</td>
					</tr>
					</tbody></table>	
			</div>
					
			<!-- /mobile banner -->
		</div>
		<!-- END VIEW PARTIAL: banner.phtml -->
		
		<!-- START VIEW PARTIAL: hotel/item list -->
		<!-- Hotel List -->
				
		<div class="clearfix"></div>
		
				<!-- /Hotel List -->
	
		<!-- END VIEW PARTIAL: hotel/item list -->
	</div>
	
	<!-- include external js -->
	<script src="http://code.jquery.com/jquery.js"></script>
	<script src="bootstrap/js/bootstrap.min.js"></script>
	<!-- /include external js -->

</body></html>