<script id="header-template" type="text/x-handlebars-template">
    <!-- Navigation -->
    <div class="row">
        <!-- Logo  -->
        <a href="//www.hotelclub.com" title="HotelClub" target="_blank">
            <img src="/n/themes/deals/images/assets/HotelClub-Logo.png" class="logo"/>
        </a>
        <!-- End Logo -->

        <!-- Tagline -->
        <span class="tag-line">{{trans.more_extraordinary_with_every_stay}}</span>
        <!-- End Tagline -->
        <div class="user"><!-- Fix this Div - Has witdth issues -->
			<div class="locale-section">
				<div class="club-id">
					<div class="locale-drop-down-arrow">
						<a>
							<span class="user-club-info">
								<img src="/n/themes/deals/images/assets/blank.gif" class="flag flag-au" alt="Australia" />
							</span>
						</a>
					</div>
					<div class="locale-wrapper">
						<div class="locale-menu">
							<ul class="locale-list">
								<li>
									<a data-locale="en_AU">
										<div class="flag-pos">
										<img src="/n/themes/deals/images/assets/blank.gif" class="flag flag-au" alt="Australia" /></div>
										<div class="flag-txt-pos">English</div>
									</a>
								</li>
								<li>
									<a data-locale="zh_TW">
									<div class="flag-pos">
									<img src="/n/themes/deals/images/assets/blank.gif" class="flag flag-tw" alt="繁體中文 (台灣)" /></div>
									<div class="flag-txt-pos">繁體中文 (台灣)</div>
									</a>
								</li>
								<li>
									<a data-locale="zh_CN">
									<div class="flag-pos">
									<img src="/n/themes/deals/images/assets/blank.gif" class="flag flag-cn" alt="简体中文" /></div>
									<div class="flag-txt-pos">简体中文</div>
									</a>
								</li>
								<li>
									<a data-locale="zh_HK">
									<div class="flag-pos">
									<img src="/n/themes/deals/images/assets/blank.gif" class="flag flag-hk" alt="繁體中文 (香港)" /></div>
									<div class="flag-txt-pos">繁體中文 (香港)</div>
									</a>
								</li>
								<li>
									<a data-locale="ms_MY">
									<div class="flag-pos">
									<img src="/n/themes/deals/images/assets/blank.gif" class="flag flag-my" alt="Bahasa Malaysia" /></div>
									<div class="flag-txt-pos">Bahasa Malaysia</div>
									</a>
								</li>
								<li>
									<a data-locale="de_DE">
									<div class="flag-pos">
									<img src="/n/themes/deals/images/assets/blank.gif" class="flag flag-de" alt="Deutsch" /></div>
									<div class="flag-txt-pos">Deutsch</div>
									</a>
								</li>
								<li>
									<a data-locale="es_ES">
									<div class="flag-pos">
									<img src="/n/themes/deals/images/assets/blank.gif" class="flag flag-es" alt="Español" /></div>
									<div class="flag-txt-pos">Español</div>
									</a>
								</li>
								<li>
									<a data-locale="fr_FR">
									<div class="flag-pos">
									<img src="/n/themes/deals/images/assets/blank.gif" class="flag flag-fr" alt="Français<" /></div>
									<div class="flag-txt-pos">Français</div>
									</a>
								</li>
								<li>
									<a data-locale="id_ID">
									<div class="flag-pos">
									<img src="/n/themes/deals/images/assets/blank.gif" class="flag flag-id" alt="Bahasa Indonesia" /></div>
									<div class="flag-txt-pos">Bahasa Indonesia</div>
									</a>
								</li>
								<li>
									<a data-locale="it_IT">
									<div class="flag-pos">
									<img src="/n/themes/deals/images/assets/blank.gif" class="flag flag-it" alt="Italiano" /></div>
									<div class="flag-txt-pos">Italiano</div>
									</a>
								</li>
								<li>
									<a data-locale="ja_JP">
									<div class="flag-pos">
									<img src="/n/themes/deals/images/assets/blank.gif" class="flag flag-jp" alt="日本語" /></div>
									<div class="flag-txt-pos">日本語</div>
									</a>
								</li>
								<li>
									<a data-locale="ko_KR">
									<div class="flag-pos">
									<img src="/n/themes/deals/images/assets/blank.gif" class="flag flag-kr" alt="한국어" /></div>
									<div class="flag-txt-pos">한국어</div>
									</a>
								</li>
								<li>
									<a data-locale="nl_NL">
									<div class="flag-pos">
									<img src="/n/themes/deals/images/assets/blank.gif" class="flag flag-nl" alt="Nederlands" /></div>
									<div class="flag-txt-pos">Nederlands</div>
									</a>
								</li>
								<li>
									<a data-locale="pl_PL">
									<div class="flag-pos">
									<img src="/n/themes/deals/images/assets/blank.gif" class="flag flag-pl" alt="Polski" /></div>
									<div class="flag-txt-pos">Polski</div>
									</a>
								</li>
								<li>
									<a data-locale="pt_PT">
									<div class="flag-pos">
									<img src="/n/themes/deals/images/assets/blank.gif" class="flag flag-pt" alt="Português" /></div>
									<div class="flag-txt-pos">Português</div>
									</a>
								</li>
								<li>
									<a data-locale="ru_RU">
									<div class="flag-pos">
									<img src="/n/themes/deals/images/assets/blank.gif" class="flag flag-ru" alt="Русский" /></div>
									<div class="flag-txt-pos">Русский</div>
									</a>
								</li>
								<li>
									<a data-locale="sv_SE">
									<div class="flag-pos">
									<img src="/n/themes/deals/images/assets/blank.gif" class="flag flag-sv" alt="Svenska" /></div>
									<div class="flag-txt-pos">Svenska</div>
									</a>
								</li>
								<li>
									<a data-locale="th_TH">
									<div class="flag-pos">
									<img src="/n/themes/deals/images/assets/blank.gif" class="flag flag-th" alt="ไทย" /></div>
									<div class="flag-txt-pos">ไทย</div>
									</a>
								</li>
							</ul>
						</div>
					</div>
				</div><!-- End User ID <ul> -->
			</div><!-- End Locale -->
			
			<div class="currency-section">
				<div class="club-id-currency">
						<div class="user-space">
							<span class="user-club-info drop-down-arrow">$AUD</span>
						</div>
					<div class="currency-wrapper">
						<div class="currency-box">
							<ul class="currencySelector selector multiColumn">
								<li class="currency-col"> <!-- Col -->
									<div class="mostUsed cur-section">
										<h5 class="Countries">Most-used currencies</h5>
										<ul>
											<li data-component="currencySelectorItem">
											<span class="current" title="AUD - Australian Dollar" data-curr="AUD">$AUD<span class="desc"> - Australian Dollar</span></span>
											</li>

											<li data-component="currencySelectorItem">
												<span class="link" title="CNY - Chinese Yuan" data-curr="CNY">¥CNY<span class="desc"> - Chinese Yuan</span></span>
											</li>

											<li data-component="currencySelectorItem">
												<span class="link" title="EUR - Euro" data-curr="EUR">€EUR<span class="desc"> - Euro</span></span>
											</li>

											<li data-component="currencySelectorItem">
												<span class="link" title="GBP - British Pound Sterling" data-curr="GBP">£GBP<span class="desc"> - British Pound Sterling</span></span>
											</li>

											<li data-component="currencySelectorItem">
												<span class="link" title="NZD - New Zealand Dollar" data-curr="NZD">$NZD<span class="desc"> - New Zealand Dollar</span></span>
											</li>

											<li data-component="currencySelectorItem">
												<span class="link" title="USD - US Dollar" data-curr="USD">$USD<span class="desc"> - US Dollar</span></span>
											</li>
										</ul>
									</div>
									<div class="cur-section top">
										<h5 class="Countries">Africa</h5>
										<ul>
											<li data-component="currencySelectorItem">
											<span class="link" title="ZAR - South African Rand" data-curr="ZAR">R ZAR<span class="desc"> - South African Rand</span></span>
											</li>
										</ul>
									</div>								
									<div class="cur-section top">
										<h5 class="Countries">Americas</h5>
										<ul>
											<li data-component="currencySelectorItem">
												<span class="link" title="BRL - Brazilian Real" data-curr="BRL">R$BRL<span class="desc"> - Brazilian Real</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="CAD - Canadian Dollar" data-curr="CAD">$CAD<span class="desc"> - Canadian Dollar</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="COP - Colombia Peso" data-curr="COP">$COP<span class="desc"> - Colombia Peso</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="MXN - Mexican Peso" data-curr="MXN">$MXN<span class="desc"> - Mexican Peso</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="USD - US Dollar" data-curr="USD">$USD<span class="desc"> - US Dollar</span></span>
											</li>
										</ul>
									</div>
								</li>
							
								<li class="currency-col currency-col-space currency-col-divide"> <!-- Col -->
									<div class="cur-section center">
										<h5 class="Countries">Asia</h5>
										<ul>
											<li data-component="currencySelectorItem">
												<span class="link" title="CNY - Chinese Yuan" data-curr="CNY">¥CNY<span class="desc"> - Chinese Yuan</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="HKD - Hong Kong Dollar" data-curr="HKD">$HKD<span class="desc"> - Hong Kong Dollar</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="IDR - Indonesia Rupiah" data-curr="IDR">RpIDR<span class="desc"> - Indonesia Rupiah</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="INR - Indian Rupee" data-curr="INR">₹INR<span class="desc"> - Indian Rupee</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="JPY - Japanese Yen" data-curr="JPY">¥JPY<span class="desc"> - Japanese Yen</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="KRW - South Korean Won" data-curr="KRW">₩KRW<span class="desc"> - South Korean Won</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="MYR - Malaysian Ringgit" data-curr="MYR">RM MYR<span class="desc"> - Malaysian Ringgit</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="PHP - Philippine Peso" data-curr="PHP">₱PHP<span class="desc"> - Philippine Peso</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="SGD - Singapore Dollar" data-curr="SGD">$SGD<span class="desc"> - Singapore Dollar</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="THB - Thai Baht" data-curr="THB">฿THB<span class="desc"> - Thai Baht</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="TWD - New Taiwan Dollar" data-curr="TWD">$TWD<span class="desc"> - New Taiwan Dollar</span></span>
											</li>
										</ul>
									</div>
									
									<div class="cur-section center top">
										<h5 class="Countries">Middle East</h5>
										<ul>
											<li data-component="currencySelectorItem">
												<span class="link" title="AED - UAE Dirham" data-curr="AED">د.إAED<span class="desc"> - UAE Dirham</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="ILS - Israeli New Sheqel" data-curr="ILS">>₪ILS<span class="desc"> - Israeli New Sheqel</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="QAR - Qatar Rial" data-curr="QAR">>ر.قQAR<span class="desc"> - Qatar Rial</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="SAR - Saudi Arabia Riyal" data-curr="SAR">>ر.سSAR<span class="desc"> - Saudi Arabia Riyal</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="TRY - Turkish Lira" data-curr="TRY">TRY<span class="desc"> - Turkish Lira</span></span>
											</li>
										</ul>
									</div>
								</li>
							
								<li class="currency-col currency-col-space"> <!-- Col -->
									<div class="cur-section">
										<h5 class="Countries">Europe</h5>
										<ul>
											<li data-component="currencySelectorItem">
												<span class="link" title="CHF - Swiss Franc" data-curr="CHF">FrCHF<span class="desc"> - Swiss Franc</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="CZK - Czech Republic Koruna" data-curr="CZK">KčCZK<span class="desc"> - Czech Republic Koruna</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="DKK - Danish Krone" data-curr="DKK">krDKK<span class="desc"> - Danish Krone</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="EUR - Euro" data-curr="EUR">€EUR<span class="desc"> - Euro</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="GBP - British Pound Sterling" data-curr="GBP">£GBP<span class="desc"> - British Pound Sterling</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="HUF - Hungary Forint" data-curr="HUF">FtHUF<span class="desc"> - Hungary Forint</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="NOK - Norwegian Krone" data-curr="NOK">krNOK<span class="desc"> - Norwegian Krone</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="PLN - Polish Zloty" data-curr="PLN">złPLN<span class="desc"> - Polish Zloty</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="RUB - Russian Ruble" data-curr="RUB">₽RUB<span class="desc"> - Russian Ruble</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="SEK - Swedish Krona" data-curr="SEK">krSEK<span class="desc"> - Swedish Krona</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="UAH - Ukrainian Hryvnia" data-curr="UAH">₴UAH<span class="desc"> - Ukrainian Hryvnia</span></span>
											</li>
										</ul>
									</div>
									<div class="cur-section top">
										<h5 class="Countries">Oceania</h5>
										<ul>
											<li data-component="currencySelectorItem">
												<span class="current" title="AUD - Australian Dollar" data-curr="AUD">$AUD<span class="desc"> - Australian Dollar</span></span>
											</li>
											<li data-component="currencySelectorItem">
												<span class="link" title="NZD - New Zealand Dollar" data-curr="NZD">$NZD<span class="desc"> - New Zealand Dollar</span></span>
											</li>
										</ul>
									</div>
								</li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
				</div>
			</div><!-- End Currency -->

            <div class="logged-in-user">
                <div class="club-section">
                    <div class="user-id">
                        <a>
                            <p><span class="user-member">Your Club</span><br/>
                                <span class="user-club-info points-token usr-rewards-point"><span class="rewards">{{trans.member_rewards}}</span></span></p>
                        </a>
                    </div>
                </div><!-- End Club -->

                <div class="member-section">
                    <div class="user-id">
                        <a>
                            <p><span class="user-member user-member-name"></span><br/>
                                <span class="user-club-info user-club-info-card-type"></span></p>
                        </a>
                    </div>
                </div><!-- End Members -->
            </div>

            <div class="logged-out-user">
                <div class="member-section">
                    <div class="user-id">

                   <p><span class="user-member user-member-name">{{trans.welcome_to_hotelclub}}</span><br/>
                    <a id="sign-in" href="https://www.hotelclub.com/account/login?destinationUrl=http://hotelclub.com/n/sale/deals/">
                        <span class="user-club-info user-club-info-card-type">{{trans.sign_in}}</span>
                    </a> /
                       <a id="register" href="https://www.hotelclub.com/account/registration?destinationUrl=http://hotelclub.com/n/sale/deals/">
                           <span class="user-club-info user-club-info-card-type">{{trans.register}}</span>
                       </a>
                   </p>

                    </div>
                </div><!-- End Members -->
            </div>

        </div><!-- End User -->

    </div> <!-- End Row -->
    <!-- End Navigation -->

    <div class="row hero-message"><a id="mid-year-sale-logo" href="/n/sale/deals/">
        <img src="/n/themes/deals/images/assets/MYS-Logo.png" align="The extraordinary mid year sale - HotelClub" style="padding-bottom:10px;" />
    </a>
    </div> <!-- End Row -->

    <div class="row search-sale-box">
        <div class="row find-your">
            <h2>{{trans.header_search_text}}</h2>
        </div>
        <div class="row">
            <div class="four columns">
               <select name="" class="hotel-dropdown-select dropdown-region input-default-value" data-rm-val="dropdown-region"></select>
            </div> <!-- End 4 Col -->
            <div class="four columns">
                <select name="" class="hotel-dropdown-select dropdown-cities input-default-value" data-rm-val="dropdown-cities"></select>
            </div> <!-- End 4 Col -->
            <div class="four columns">
                <select name="" class="hotel-dropdown-select dropWhereDo input-default-value" data-rm-val="dropWhereDo"></select>
            </div> <!-- End 4 Col -->
        </div> <!-- End Row -->
    </div>

    <div class="row hero-space">
        &nbsp;
    </div> <!-- End Row -->
</script>