<script id="select-popup-template" type="text/x-handlebars-template">

    <div class="select-dates">
    <input name="" type="hidden" id="selected-oneg" value="" />
    <div class="select-dates-close-window">
    <h3 class="select-date-hotel-name">&nbsp;</h3>
    <span class="close-select-dates" title="Close">{{trans.close}}</span>
    </div>

    <div class="select-dates-container">
    <div class="select-lable">{{trans.select_dates_hotel_stay}}</div>
    <div class="select-dates-row">
    <div class="select-validation-message"></div>
    <div class="select-dates-in-out">
    <p>Check in<br />
    <input name="" type="text" class="select-dates-input" id="select-check-in" value="{{trans.select_date_format}}"/>
    <input type="text" id="alternate-check-in" class="select-label-val" readonly/></p>
    </div>
    <div class="select-dates-in-out">
    <p>Check out<br />
    <input name="" type="text" class="select-dates-input" id="select-check-out" value="{{trans.select_date_format}}"/>
    <input type="text" id="alternate-check-out" class="select-label-val" readonly/></p>
    </p>
    </div>
    <div class="select-dates-nights">
    <p>Nights<br />
    <input name="" type="text" class="select-dates-display" value="0"/></p>
    </div>
    </div><!-- End row -->

    <div class="select-dates-row room-divide1">
    <div class="select-dates-room">
    <p>{{trans.room}} 1</p>
    </div>
    <div class="select-dates-humans">
    <p>{{trans.adult}} <small>(18+)</small><br />
    <select name="adult-input-1" class="select-dates-input-popup" id="adult-input-1">
    <option value='1'>1</option>
    <option value='2' selected>2</option>
    <option value='3'>3</option>
    <option value='4'>4</option>
    </select></p>
    </div>
    <div class="select-dates-humans room1">
    <p>{{trans.child}} <small>(0-17)</small><br />
    <select name="child-input-1" class="select-dates-input-popup" id="child-input-1">
    <option value='0'>---</option>
    <option value='1'>1</option>
    <option value='2'>2</option>
    <option value='3'>3</option>
    <option value='4'>4</option>
    <option value='5'>5</option>
    </select></p>
    </div>
    <div class="room-1">
    </div>
    </div><!-- End room -->

    <div class="select-dates-add-remove">
    <small>{{trans.if_you_travelling_text}} 1</small><br />
    </div>
    <div class="add-remove-lable"><small><span class="add-room">{{trans.add_room}}</span> <span class="divider-room"> | </span><span class="remove-room"> {{trans.remove_room}}</span></small></div>
    <div class="select-dates-row">
    <div class="select-dates-footer"><input type="text" id="promo-code-val" class="select-dates-input" value="{{trans.promo_code}}" data-value="Promo code" maxlength="30" /></div><a title="Find a room" class="select-dates-button find-btn">{{trans.find}}</a>
    </div><!-- End Button -->
    </div>
    </div>
</script>

<script id="hotel-card-template" type="text/x-handlebars-template">
    {{#each hData}}

    <div class="hotelcards">
        <!-- Card 1 -->
        <div class="card">
            <div class="card-image">

                {{displayExclusiveBanner promotion ../isLoggedIn}}

                <!-- Dynamic hotel id value will be replaced here.. -->

                <a href="//www.hotelclub.com/shop/hotelsearch?type=hotel&locale=en_AU&hotel.hid={{hotelId}}&hotel.hname={{hotelNameUtf8}}&hsv.showDetails=true&hotel.type=keyword&hotel.chkin=&hotel.chkout=&hotel.keyword.key=0&hotel.rooms[0].adlts=2&search=Search"
                   target="_blank">
                    <img class="lazy card-img" data-original="{{thImgUrl}}"/>
                </a>
            </div>
            <div class="card-info">
                <div class="hotel-name">
                    <!-- Dynamic hotel id value will be replaced here.. -->
                    <a href="//www.hotelclub.com/shop/hotelsearch?type=hotel&locale=en_AU&hotel.hid={{hotelId}}&hotel.hname={{hotelNameUtf8}}&hsv.showDetails=true&hotel.type=keyword&hotel.chkin=&hotel.chkout=&hotel.keyword.key=0&hotel.rooms[0].adlts=2&search=Search"
                       target="_blank" class="hotel-name-head">{{{trimString hotelNameUtf8 40}}}</a></div>
                <div class="card-desc">
                    <div class="card-left">
                        <div class="star-sprite-{{starRating}}">
                        </div>
                        {{displayPromotions promotion ../isLoggedIn}}
					</div>
					<div class="card-right">

                        {{#isTrue ../isLoggedIn}}
						<div class="hotel-member">
                            <span class="member-price-title">Member price</span>
						&nbsp;<div class="member-q">
							<div class="member-info">?</div>
							<div class="member-info-desc">
								<div class="member-info-top"><div class="member-info-close">{{trans.close}}</div></div>
								<div class="member-info-middle">{{trans.member_price_text}}</div>
								<div class="member-info-bottom">&nbsp;</div>
							</div>
						</div></div>
                        {{/isTrue}}

						<p class="hotel-price">{{curySymbole}}{{displayPrice price ../memberPrice}}</p>
						<p class="hotel-avg">avg/night</p>
						<span class="hotel-card-button" data-onegid="{{hotelId}}" data-hotel='{{{hotelNameUtf8}}}'>Select dates &gt;</span>
					</div>
				</div>
            </div>
        </div><!-- End Card 1 -->
    </div><!-- End Card Container -->
    {{/each}}
</script>