<script id="orbot-template" type="text/x-handlebars-template">
    <div class="modal-wrapper">
        <div class="modal-box">
            <div class="modal-container">
                <div class="modal-row">
                    <p class="cancel-action"><small>close</small></p>
                    <h3>Search all of HotelClub</h3>
                </div>
                <div class="modal-row orbot-validation-message" style="color:red !important;"></div>
                <div class="modal-row">
                    <p>Where would you like to go?<br />
                        <input name="" type="text" class="modal-input modal-marker robot-city-name" value="{{city}}"/></p>
                </div>
                <div class="modal-row" data-row="0">
                    <div class="six columns">
                        <p>Check-in and Check-out<br />
                        <div class="modal-calendar">
                            <!--<select name="" class="modal-dropdown-select-date">
                                <option>JQuery date picker</option>
                            </select>-->
                            <input name="check-in" type="text" class="modal-input-date" id="check-in" value="dd/mm/yy"/>&nbsp;
                            <input name="check-out" type="text" class="modal-input-date" id="check-out" value="dd/mm/yy"/><br/>
							<input type="text" id="alt-check-in" class="select-label-val" readonly/>&nbsp;
							<input type="text" id="alt-check-out" class="select-label-val readonly"/>
                        </div></p>
                    </div>
                    <div class="six columns">
                        <div class="four columns">
                            <p>Rooms<br />
                                <select name="" class="modal-dropdown-select orbot-select-rooms">
                                    <option value="1">Room 1</option>
                                    <option value="2">Room 2</option>
                                    <option value="3">Room 3</option>
                                    <option value="4">Room 4</option>
                                    <option value="5">Room 5</option>
                                </select></p>
                        </div>
                        <div class="four columns">
                            <p>Adults (18+)<br />
                                <select name="" class="modal-dropdown-select orb-adults-0">
                                    <option>1</option>
                                    <option selected>2</option>
                                    <option>3</option>
                                    <option>4</option>
                                    <option>5</option>
                                    <option>6</option>
                                </select></p>
                        </div>
                        <div class="four columns">
                            <p>Children (0-17)<br />
                                <select name="" class="modal-dropdown-select orbot-select-children orb-child-0">
                                    <option>--</option>
                                    <option>1</option>
                                    <option>2</option>
                                    <option>3</option>
                                    <option>4</option>
                                    <option>5</option>
                                </select></p>
                        </div>
                    </div>
                </div>
                <div class="modal-row">
                    <div class="six columns">
                        <p>Search hotel name<br />
                            <input name="" type="text" class="modal-input search-hotel-name" value="e.g. Sydney Hilton"/></p>
                    </div>
                    <div class="six columns">
                        <p>Apply promo code<br />
                            <input name="" type="text" class="modal-input" value="Enter code"/></p>
                    </div>
                </div>
                <div class="modal-row">
                    <div class="twelve columns">
                        <a href="" title="Search" class="modal-row-button">Search hotels</a>
                    </div>
                    <div class="twelve columns">
                    </div>
                </div>
            </div>
        </div>
    </div>

</script>