<script id="sort-template" type="text/x-handlebars-template">
<div class="row sort-row">
    <div class="three columns" id="filter-btn">
        <ul class="breadcrumbs bc-space">
            <li><a id="breadcrumb-home" href="/n/sale/deals/">{{trans.home}}</a></li>
            >
            <li id="breadcrumb-city">{{ city }}</li>
        </ul>
    </div>
    <div class="nine columns">
        <ul class="sort-control sr-space">
            <li class="sort-list sort-list-label">
                {{trans.sort_by}}:
            </li>
            <li class="sort-list">
                <a class="sort-button sort-box-price" data-sort="price" title="Price">{{trans.price}}</a>
            </li>
            <li class="sort-list">
                <a class="sort-button sort-box-name" data-sort="name" title="Name">{{trans.name}}</a>
            </li>
            <li class="sort-list">
                <a class="sort-button sort-box-rating" data-sort="rating" title="Rating">{{trans.rating}}</a>
            </li>
            <li class="sort-list">
                <strong><a class="sort-button sort-box-picks" data-sort="ourPicks" title="Our picks">{{trans.our_picks}}</a>
                <span class="sort-indicator-image"></span> <!-- &or; --></strong>
            </li>
        </ul>
    </div>
</div>
</script>